// A2 Mini Drills per lesson
module.exports = {
  A2_lesson_1: [
    { prompt: "___ du aus Spanien? (kommen)", answer: "Kommst" },
    { prompt: "Ich ___ keine Geschwister. (haben)", answer: "habe" },
    { prompt: "Mein ___ Bruder heißt Max.", answer: "mein (or der)" },
    { prompt: "___ heißen Sie?", answer: "Wie" },
    { prompt: "Nein, ich komme ___ aus Italien. (nicht/kein)", answer: "nicht" },
  ],
  A2_lesson_2: [
    { prompt: "___ Sie mir bitte helfen? (Modalverb)", answer: "Können" },
    { prompt: "___ (du) bitte leise!", answer: "Sei" },
    { prompt: "Um 7 Uhr ___ ich auf. (aufstehen, Präsens)", answer: "stehe" },
    { prompt: "Früher ___ ich jeden Tag schwimmen. (gehen, Präteritum)", answer: "ging" },
    { prompt: "___ du heute Abend Zeit?", answer: "Hast" },
  ],
  A2_lesson_3: [
    { prompt: "Ich habe gestern ___ (einkaufen).", answer: "eingekauft" },
    { prompt: "Er ___ nach Berlin gefahren. (Hilfsverb)", answer: "ist" },
    { prompt: "___ du das Buch gelesen?", answer: "Hast" },
    { prompt: "Wir sind um 8 Uhr ___ (abfahren).", answer: "abgefahren" },
    { prompt: "Sie hat den Kuchen ___ (backen).", answer: "gebacken" },
  ],
  A2_lesson_4: [
    { prompt: "___ ich gestern im Park war, hat es geregnet. (one-time past)", answer: "Als" },
    { prompt: "___ du Zeit hast, können wir uns treffen.", answer: "Wenn" },
    { prompt: "Ich reise gern, ___ ich neue Orte entdecke. (because)", answer: "weil" },
    { prompt: "Das Hotel ist größer ___ die Kirche.", answer: "als" },
    { prompt: "___ das Wetter gut ist, gehen wir spazieren.", answer: "Wenn" },
  ],
  A2_lesson_5: [
    { prompt: "Ich bleibe zu Hause, ___ es regnet.", answer: "weil" },
    { prompt: "___ ich krank bin, gehe ich zum Arzt.", answer: "Weil" },
    { prompt: "Er lernt Deutsch, ___ er in Berlin wohnt.", answer: "weil" },
    { prompt: "___ es kalt ist, ziehe ich eine Jacke an.", answer: "Weil" },
    { prompt: "Sie kommt nicht, ___ sie keine Zeit hat.", answer: "weil" },
  ],
  A2_lesson_6: [
    { prompt: "Kannst du mir sagen, ___ der Bahnhof ist?", answer: "wo" },
    { prompt: "Ich möchte wissen, ___ er morgen kommt. (yes/no)", answer: "ob" },
    { prompt: "Weißt du, ___ das kostet?", answer: "was" },
    { prompt: "Ich frage mich, ___ sie schon da ist.", answer: "ob" },
    { prompt: "Können Sie mir erklären, ___ ich das mache?", answer: "wie" },
  ],
  A2_lesson_7: [
    { prompt: "Das ist ein ___ Wein. (gut - Nominativ)", answer: "guter" },
    { prompt: "Ich möchte ein ___ Bier. (kalt - Akkusativ)", answer: "kaltes" },
    { prompt: "Die ___ Suppe schmeckt gut. (warm - bestimmt)", answer: "warme" },
    { prompt: "Er kauft einen ___ Käse. (frisch - Akkusativ)", answer: "frischen" },
    { prompt: "Mit einem ___ Salat, bitte. (klein - Dativ)", answer: "kleinen" },
  ],
  A2_lesson_8: [
    { prompt: "Früher ___ ich nicht so gut Deutsch sprechen. (können, Prät.)", answer: "konnte" },
    { prompt: "Er ___ gestern arbeiten. (müssen, Prät.)", answer: "musste" },
    { prompt: "___ du das Fenster öffnen?", answer: "Kannst" },
    { prompt: "Wir ___ das nicht machen. (sollen, Prät.)", answer: "sollten" },
    { prompt: "Das Kind ___ ins Bett gehen. (wollen, Prät.)", answer: "wollte" },
  ],
  A2_lesson_9: [
    { prompt: "Ich denke, ___ du Recht hast.", answer: "dass" },
    { prompt: "Er sagt, ___ er morgen kommt.", answer: "dass" },
    { prompt: "Ich hoffe, ___ du mich verstehst.", answer: "dass" },
    { prompt: "Wir wissen, ___ Deutsch nicht einfach ist.", answer: "dass" },
    { prompt: "Glaubst du, ___ er die Prüfung schafft?", answer: "dass" },
  ],
  A2_lesson_10: [
    { prompt: "Das Buch liegt ___ dem Tisch. (on top of)", answer: "auf" },
    { prompt: "Ich lege das Buch ___ den Tisch. (onto)", answer: "auf" },
    { prompt: "Die Katze ist ___ dem Bett. (under, location)", answer: "unter" },
    { prompt: "Ich gehe ___ die Stadt. (into)", answer: "in" },
    { prompt: "Er hängt das Bild ___ die Wand. (to the wall)", answer: "an" },
  ],
  A2_lesson_11: [
    { prompt: "Ich wasche ___ die Hände.", answer: "mir" },
    { prompt: "Er fühlt ___ krank.", answer: "sich" },
    { prompt: "Wir ___ uns auf den Urlaub. (freuen)", answer: "freuen" },
    { prompt: "Kannst du ___ helfen? (Dativ)", answer: "mir" },
    { prompt: "Sie kämmt ___ die Haare.", answer: "sich" },
  ],
  A2_lesson_12: [
    { prompt: "___ Sie bitte Platz! (nehmen)", answer: "Nehmen" },
    { prompt: "___ (du) mir das Salz!", answer: "Gib" },
    { prompt: "___ (ihr) bitte leise!", answer: "Seid" },
    { prompt: "Bitte ___ Sie hier! (unterschreiben)", answer: "unterschreiben" },
    { prompt: "___ (du) nicht so schnell!", answer: "Fahr" },
  ],
  A2_lesson_13: [
    { prompt: "Früher ___ ich in Berlin. (wohnen, Prät.)", answer: "wohnte" },
    { prompt: "Letzte Woche ___ das Wetter schön. (sein, Prät.)", answer: "war" },
    { prompt: "___ 8 Uhr beginnt der Unterricht.", answer: "Um" },
    { prompt: "Im ___ ist es heiß. (Sommer)", answer: "Sommer" },
    { prompt: "Gestern ___ ich keine Zeit. (haben, Prät.)", answer: "hatte" },
  ],
  A2_lesson_14: [
    { prompt: "Deutsch ist ___ (schwer) als Englisch.", answer: "schwerer" },
    { prompt: "Das ist der ___ (groß) See in Deutschland.", answer: "größte" },
    { prompt: "Mein Bruder läuft ___ (schnell) als ich.", answer: "schneller" },
    { prompt: "Sie singt am ___ (gut).", answer: "besten" },
    { prompt: "Dieses Buch ist ___ (interessant) als das andere.", answer: "interessanter" },
  ],
  A2_lesson_15: [
    { prompt: "Ich gehe ___ ins Kino ___ meinem Freund. (time then place)", answer: "heute ... mit" },
    { prompt: "___ gehst du, ___ bleibst du?", answer: "Gehst ... oder" },
    { prompt: "Ich mag Tee, ___ ich trinke Kaffee.", answer: "aber" },
    { prompt: "Er kommt nicht, ___ er krank ist.", answer: "denn" },
    { prompt: "___ wir essen, bestellen wir erst.", answer: "Bevor/Erst" },
  ],
  A2_lesson_16: [
    { prompt: "Ich gebe ___ Kind ein Geschenk. (Dativ)", answer: "dem" },
    { prompt: "Er hilft ___ Mutter. (Dativ)", answer: "der" },
    { prompt: "Das gehört ___ Bruder. (mein - Dativ)", answer: "meinem" },
    { prompt: "Sie dankt ___ Freund. (ihr - Dativ)", answer: "ihrem" },
    { prompt: "Wir danken ___ Lehrerin. (Dativ)", answer: "der" },
  ],
  A2_lesson_17: [
    { prompt: "Ich wasche ___ die Hände. (reflexiv)", answer: "mir" },
    { prompt: "Er putzt ___ die Zähne.", answer: "sich" },
    { prompt: "Sie kämmt ___ die langen Haare.", answer: "sich" },
    { prompt: "Ich fühle ___ heute besser.", answer: "mich" },
    { prompt: "Er sieht ___ im Spiegel an.", answer: "sich" },
  ],
  A2_lesson_18: [
    { prompt: "Sie trägt ein ___ Kleid. (rot - Akk. n)", answer: "rotes" },
    { prompt: "Er kauft einen ___ Anzug. (blau - Akk. m)", answer: "blauen" },
    { prompt: "Mit einer ___ Jacke. (warm - Dativ f)", answer: "warmen" },
    { prompt: "Dieser Rock ist ___ (kurz) als der andere.", answer: "kürzer" },
    { prompt: "Das ist das ___ (schön) Kleid.", answer: "schönste" },
  ],
  A2_lesson_19: [
    { prompt: "Das ist das Auto ___ Vaters. (Genitiv)", answer: "des" },
    { prompt: "Die Tasche ___ Mutter ist neu. (Genitiv)", answer: "der" },
    { prompt: "Das Haus ___ Freundes ist groß. (mein - Genitiv)", answer: "meines" },
    { prompt: "Die Farbe ___ Himmels ist blau. (Genitiv)", answer: "des" },
    { prompt: "Der Name ___ Kindes ist Lukas. (Genitiv)", answer: "des" },
  ],
  A2_lesson_20: [
    { prompt: "Weißt du, ___ dieses Gerät funktioniert? (how)", answer: "wie" },
    { prompt: "Kannst du mir sagen, ___ ich die App installiere?", answer: "wie" },
    { prompt: "Ich frage mich, ___ das Internet wieder funktioniert. (whether)", answer: "ob" },
    { prompt: "Er erklärt mir, ___ Programm ich brauche. (which)", answer: "welches" },
    { prompt: "Ich weiß nicht, ___ mein Handy ist. (where)", answer: "wo" },
  ],
  A2_lesson_21: [
    { prompt: "Der Löwe ist ___ (stark) als der Fuchs.", answer: "stärker" },
    { prompt: "Das Pferd läuft ___ (schnell) als der Esel.", answer: "schneller" },
    { prompt: "Der Hund ist der ___ (treu) Freund des Menschen.", answer: "treueste" },
    { prompt: "___ ich im Wald spazieren gehe, sehe ich oft Rehe.", answer: "Wenn" },
    { prompt: "Die Katze ist ___ (klein) als der Hund.", answer: "kleiner" },
  ],
  A2_lesson_22: [
    { prompt: "Ich ___ über das Geschenk. (sich freuen)", answer: "freue mich" },
    { prompt: "Er ___ vor der Prüfung. (sich fürchten)", answer: "fürchtet sich" },
    { prompt: "Wir ___ im Urlaub. (sich erholen)", answer: "erholen uns" },
    { prompt: "___ ihr über den Film? (sich ärgern)", answer: "Ärgert euch" },
    { prompt: "Sie ___ sich heute nicht gut.", answer: "fühlt" },
  ],
  A2_lesson_23: [
    { prompt: "Ich komme ___ der Schweiz. (from)", answer: "aus" },
    { prompt: "Er wohnt ___ seiner Familie. (with)", answer: "bei" },
    { prompt: "Ich fahre ___ dem Zug. (by)", answer: "mit" },
    { prompt: "Gehen Sie ___ der Ampel links.", answer: "an" },
    { prompt: "Die nächste U-Bahn ___ sechs Minuten. (in)", answer: "in" },
  ],
  A2_lesson_24: [
    { prompt: "___ Weihnachten kommt, schmücken wir den Baum.", answer: "Wenn" },
    { prompt: "___ ich klein war, habe ich an den Osterhasen geglaubt.", answer: "Als" },
    { prompt: "Wir feiern, ___ wir uns lange nicht gesehen haben.", answer: "weil" },
    { prompt: "___ das Fest beginnt, singen wir ein Lied.", answer: "Bevor" },
    { prompt: "___ Ostern suchen die Kinder Eier.", answer: "Zu/an" },
  ],
  A2_lesson_25: [
    { prompt: "___ ich in Deutschland ankomme, werde ich einen Kurs besuchen.", answer: "Wenn" },
    { prompt: "Ich möchte Deutsch lernen, ___ ich in Berlin studieren will.", answer: "weil" },
    { prompt: "___ ich das B1-Zertifikat habe, kann ich mich bewerben.", answer: "Wenn" },
    { prompt: "Früher ___ ich nur A1, jetzt kann ich A2. (können, Prät.)", answer: "konnte" },
    { prompt: "Ich hoffe, ___ ich bald B1 erreiche.", answer: "dass" },
  ],
};
