// Keyword -> lesson mapping for reading/listening/writing/speaking content
module.exports = [
  { k: ["tag", "morgen", "routine", "alltag", "täglich", "tägliche"], l: "A2_lesson_2" },
  { k: ["haus", "wohnung", "miete", "umzug", "nachbar", "mitbewohner", "wohnungsanzeige", "mietvertrag", "vermieter", "sperrmüll"], l: "A2_lesson_10" },
  { k: ["arbeit", "büro", "kollege", "job", "beruf", "bewerbung", "vorstellungsgespräch", "kündigung", "jobausschreibung"], l: "A2_lesson_8" },
  { k: ["urlaub", "reisen", "reise", "fahrkarte", "bahn", "flug", "zug", "wochenendausflug", "reisetagebuch", "busfahrplan", "parkplatz"], l: "A2_lesson_4" },
  { k: ["essen", "restaurant", "küche", "rezept", "speise", "speisekarte", "stornierung einer bestellung"], l: "A2_lesson_7" },
  { k: ["krank", "arzt", "schmerz", "krankenhaus", "praxis", "arzttermin", "wartezimmer", "ärztin"], l: "A2_lesson_11" },
  { k: ["apotheke", "medikament", "apotheken-information", "praxis-information", "information einhaltung von bestimmungen bei medikamenten mit betäubungsmitteln"], l: "A2_lesson_12" },
  { k: ["freizeit", "hobby", "sport", "spiel", "freund", "schwimmbad", "fitnessstudio", "kinoprogramm", "sportprogramm"], l: "A2_lesson_14" },
  { k: ["schule", "sprachkurs", "unterricht", "lernen", "kurs", "bibliothek", "elternbrief", "kursanmeldung", "kursleiter", "rückmeldung zum sprachkurs", "sprachinstitut"], l: "A2_lesson_9" },
  { k: ["geburtstag", "feier", "fest", "weihnachten", "feiertag", "geburtstagsfeier", "kindergeburtstag", "stadtfest"], l: "A2_lesson_16" },
  { k: ["kleidung", "kleid", "hemd", "schuh", "anzug", "mode"], l: "A2_lesson_18" },
  { k: ["wetter", "regen", "sonne", "schnee", "jahreszeit", "wettervorhersage", "glatteis", "sonnig"], l: "A2_lesson_13" },
  { k: ["familie", "mutter", "vater", "kind", "eltern", "geschwister", "freundschaft"], l: "A2_lesson_19" },
  { k: ["handy", "computer", "internet", "e-mail", "technik", "handyvertrag", "gerät", "anleitung für ein", "rechnung vom handyvertrag"], l: "A2_lesson_20" },
  { k: ["tier", "hund", "katze", "pferd", "natur", "waldführung"], l: "A2_lesson_21" },
  { k: ["hotel", "zimmer", "rezeption", "buchung", "hotelbestätigung"], l: "A2_lesson_5" },
  { k: ["einkaufen", "markt", "geschäft", "kaufen", "bestellung", "ware", "waren"], l: "A2_lesson_6" },
  { k: ["fühlen", "emotion", "trauer", "glück", "angst", "freude", "gefühle"], l: "A2_lesson_22" },
  { k: ["termin", "einladung", "treffen", "verabredung", "absage", "terminabsage", "ausweisverlust", "öffnungszeiten"], l: "A2_lesson_15" },
  { k: ["karte", "weg", "straße", "richtung", "verkehr", "mülltrennung", "ausweis", "abmahnung", "ausfall des schwimmbads"], l: "A2_lesson_23" },
  { k: ["körper", "kopf", "arm", "bein", "hand", "aussehen", "gesicht", "rücken", "zahn", "zähne", "nase", "auge", "ohr", "fuß"], l: "A2_lesson_17" },
  { k: ["tradition", "ostern", "museumsinformation", "museum", "festival", "weihnachten", "silvester", "neujahr"], l: "A2_lesson_24" },
  { k: ["garantie", "vertrag", "betrug", "rücktritt", "rückmeldung", "warnung", "versicherung"], l: "A2_lesson_25" },
  { k: ["einwohnermeldeamt", "anmeldung", "anmeldung beim einwohnermeldeamt"], l: "A2_lesson_10" },
  { k: ["paketankündigung", "paket", "lieferung"], l: "A2_lesson_6" },
  { k: ["nachbarschaftshilfe", "nachbarschaft"], l: "A2_lesson_10" },
  { k: ["unternehmen", "abmahnung", "rechnung", "kosten"], l: "A2_lesson_15" },
  { k: ["urlaubsgrüße", "urlaubsgrüsse", "postkarte"], l: "A2_lesson_4" },
];
