// A2 Track Tags per lesson
module.exports = {
  A2_lesson_1: ["goethe", "a2-review", "self-intro"],
  A2_lesson_2: ["goethe", "daily-life", "imperative"],
  A2_lesson_3: ["goethe", "past-tense", "perfect"],
  A2_lesson_4: ["goethe", "travel", "conjunctions"],
  A2_lesson_5: ["goethe", "accommodation", "weil-clauses"],
  A2_lesson_6: ["goethe", "shopping", "questions"],
  A2_lesson_7: ["goethe", "food", "adjective-endings"],
  A2_lesson_8: ["goethe", "work", "modal-verbs"],
  A2_lesson_9: ["goethe", "education", "dass-clauses"],
  A2_lesson_10: ["goethe", "housing", "two-way-prep"],
  A2_lesson_11: ["goethe", "health", "reflexive-verbs"],
  A2_lesson_12: ["goethe", "pharmacy", "imperative"],
  A2_lesson_13: ["goethe", "weather", "past-tense"],
  A2_lesson_14: ["goethe", "hobbies", "comparison"],
  A2_lesson_15: ["goethe", "appointments", "word-order"],
  A2_lesson_16: ["goethe", "celebrations", "dative"],
  A2_lesson_17: ["goethe", "body-parts", "reflexive-verbs"],
  A2_lesson_18: ["goethe", "clothing", "adjective-endings"],
  A2_lesson_19: ["goethe", "family", "genitive"],
  A2_lesson_20: ["goethe", "technology", "indirect-questions"],
  A2_lesson_21: ["goethe", "animals", "comparison"],
  A2_lesson_22: ["goethe", "emotions", "reflexive-verbs"],
  A2_lesson_23: ["goethe", "directions", "dative-prep"],
  A2_lesson_24: ["goethe", "traditions", "conjunctions"],
  A2_lesson_25: ["goethe", "review", "b1-preparation"],
};
