import { readFileSync, writeFileSync } from 'fs';

const path = new URL('../src/data/grammar.json', import.meta.url);
const data = JSON.parse(readFileSync(path, 'utf8'));
const existing = data.B2 || [];

console.log('Existing B2 grammar:', existing.length);

// Fix existing: add level + topic fields
const topicMap = {
  'B2_gr_1': 'Advanced Passive',
  'B2_gr_2': 'Passive with Modals',
  'B2_gr_3': 'Nominalization',
  'B2_gr_4': 'Participle Constructions',
  'B2_gr_5': 'Participle Constructions',
  'B2_gr_6': 'Connectors',
  'B2_gr_7': 'Connectors',
  'B2_gr_8': 'N-Deklination',
  'B2_gr_9': 'N-Deklination',
  'B2_gr_10': 'Extended Infinitives',
  'B2_gr_11': 'Future II',
  'B2_gr_12': 'Complex Connectors',
  'B2_gr_13': 'Subjunctive I',
  'B2_gr_14': 'Modal Verb Meanings',
  'B2_gr_15': 'Double Connectors',
  'B2_gr_16': 'Double Connectors',
  'B2_gr_17': 'Genitive Prepositions',
  'B2_gr_18': 'Verb Fixed Prepositions',
  'B2_gr_19': 'Verb Fixed Prepositions',
  'B2_gr_20': 'Complex Passive',
};

for (const ex of existing) {
  ex.level = 'B2';
  if (!ex.topic && topicMap[ex.id]) ex.topic = topicMap[ex.id];
}

const newExercises = [
  // ── Advanced Passive (5 more) ──
  { id:'B2_gr_21', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Die T\u00fcr ___ jeden Morgen um 8 Uhr ___. (\u00f6ffnen)',
    answer:'wird ge\u00f6ffnet', options:['wird ge\u00f6ffnet','ist ge\u00f6ffnet','hat ge\u00f6ffnet','wurde ge\u00f6ffnet'],
    explanation:'Vorgangspassiv Pr\u00e4sens: werden + Partizip II.' },
  { id:'B2_gr_22', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Das Haus ___ letztes Jahr ___. (bauen)',
    answer:'wurde gebaut', options:['wird gebaut','wurde gebaut','ist gebaut','hat gebaut'],
    explanation:'Passiv Pr\u00e4teritum: wurden + Partizip II.' },
  { id:'B2_gr_23', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Die Pr\u00fcfung ___ bereits ___. (korrigieren)',
    answer:'ist korrigiert worden', options:['ist korrigiert worden','wurde korrigiert','wird korrigiert','hat korrigiert'],
    explanation:'Passiv Perfekt: sein + Partizip II + worden.' },
  { id:'B2_gr_24', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Hier ___ bald ein neues Krankenhaus ___. (er\u00f6ffnen)',
    answer:'wird er\u00f6ffnet', options:['wird er\u00f6ffnet','ist er\u00f6ffnet','wurde er\u00f6ffnet','hat er\u00f6ffnet'],
    explanation:'Passiv Pr\u00e4sens mit Zeitangabe.' },
  { id:'B2_gr_25', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Die Briefe ___ gestern von der Sekret\u00e4rin ___. (schicken)',
    answer:'wurden geschickt', options:['wurden geschickt','wurde geschickt','sind geschickt','hat geschickt'],
    explanation:'Passiv Pr\u00e4teritum, Plural: wurden + Partizip II.' },

  // ── Zustandspassiv (5) ──
  { id:'B2_gr_26', level:'B2', topic:'Zustandspassiv', type:'mcq',
    prompt:'Die T\u00fcr ist geschlossen. Das ist ein ___',
    answer:'Zustandspassiv', options:['Vorgangspassiv','Zustandspassiv','Aktiv','Perfekt'],
    explanation:'Zustandspassiv beschreibt einen Zustand (sein + Partizip II).' },
  { id:'B2_gr_27', level:'B2', topic:'Zustandspassiv', type:'fill-blank',
    prompt:'Das Fenster ___. (schlie\u00dfen - Zustand)',
    answer:'ist geschlossen', options:['ist geschlossen','wird geschlossen','wurde geschlossen','hat geschlossen'],
    explanation:'Zustandspassiv: sein + Partizip II.' },
  { id:'B2_gr_28', level:'B2', topic:'Zustandspassiv', type:'fill-blank',
    prompt:'Die Rechnung ___ bereits ___. (bezahlen - Zustand)',
    answer:'ist bezahlt', options:['ist bezahlt','wird bezahlt','wurde bezahlt','hat bezahlt'],
    explanation:'Der Zustand nach der Bezahlung: sein + Partizip II.' },
  { id:'B2_gr_29', level:'B2', topic:'Zustandspassiv', type:'sentence-correction',
    prompt:'Correct: Der Tisch wird gedeckt. (Zustand = already covered)',
    answer:'Der Tisch ist gedeckt.',
    explanation:'Zustandspassiv f\u00fcr bereits abgeschlossene Handlungen.' },
  { id:'B2_gr_30', level:'B2', topic:'Zustandspassiv', type:'fill-blank',
    prompt:'Die G\u00e4ste sind schon ___. (einladen)',
    answer:'eingeladen', options:['eingeladen','geladen ein','einladet','laden ein'],
    explanation:'Zustandspassiv: sein + eingeladen.' },

  // ── Passive with Modals (5 more) ──
  { id:'B2_gr_31', level:'B2', topic:'Passive with Modals', type:'fill-blank',
    prompt:'Hier ___ kein Parkplatz ___ (d\u00fcrfen + bauen).',
    answer:'darf gebaut werden', options:['darf bauen','darf gebaut werden','wird gebaut d\u00fcrfen','darf bauen werden'],
    explanation:'Modalverb + Passiv: Modalverb + Partizip II + werden.' },
  { id:'B2_gr_32', level:'B2', topic:'Passive with Modals', type:'fill-blank',
    prompt:'Das ___ bis morgen ___ (m\u00fcssen + erledigen).',
    answer:'muss erledigt werden', options:['muss erledigen','muss erledigt werden','wird erledigt m\u00fcssen','erledigt werden muss'],
    explanation:'m\u00fcssen + Passiv: muss + Partizip II + werden.' },
  { id:'B2_gr_33', level:'B2', topic:'Passive with Modals', type:'fill-blank',
    prompt:'Die Patienten ___ gut ___ (sollen + behandeln).',
    answer:'sollen behandelt werden', options:['sollen behandeln','sollen behandelt werden','werden behandelt sollen','behandeln sollen'],
    explanation:'sollen + Passiv: sollen + Partizip II + werden.' },
  { id:'B2_gr_34', level:'B2', topic:'Passive with Modals', type:'fill-blank',
    prompt:'Das altes Auto ___ nicht mehr ___ (k\u00f6nnen + reparieren).',
    answer:'kann repariert werden', options:['kann reparieren','kann repariert werden','wird reparieren k\u00f6nnen','kann repariert worden'],
    explanation:'k\u00f6nnen + Passiv: kann + Partizip II + werden.' },
  { id:'B2_gr_35', level:'B2', topic:'Passive with Modals', type:'fill-blank',
    prompt:'Die Fenster ___ einmal pro Woche ___ (m\u00fcssen + putzen).',
    answer:'m\u00fcssen geputzt werden', options:['m\u00fcssen putzen','m\u00fcssen geputzt werden','muss geputzt werden','putzen m\u00fcssen'],
    explanation:'Modalverb Passiv, Plural: m\u00fcssen + Partizip II + werden.' },

  // ── Nominalization (5 more) ──
  { id:'B2_gr_36', level:'B2', topic:'Nominalization', type:'fill-blank',
    prompt:'Verb: ankommen \u2192 Nomen: die ___',
    answer:'Ankunft', options:['Ankunft','Ankommung','Angekommen','Ankommt'],
    explanation:'Viele Verben werden zu Nomen mit -t oder -ung Endung.' },
  { id:'B2_gr_37', level:'B2', topic:'Nominalization', type:'fill-blank',
    prompt:'Verb: entscheiden \u2192 Nomen: die ___',
    answer:'Entscheidung', options:['Entscheidung','Entscheiden','Entschied','Entscheid'],
    explanation:'-ung ist eine h\u00e4ufige Endung f\u00fcr Nominalisierungen.' },
  { id:'B2_gr_38', level:'B2', topic:'Nominalization', type:'mcq',
    prompt:'"Er forscht an der Uni." \u2192 "Er arbeitet in der ___."',
    answer:'Forschung', options:['Forschung','Forscher','Geforsche','Forscht'],
    explanation:'forschen \u2192 die Forschung (Wissenschaft).' },
  { id:'B2_gr_39', level:'B2', topic:'Nominalization', type:'fill-blank',
    prompt:'Verb: pr\u00fcfen \u2192 Nomen: die ___',
    answer:'Pr\u00fcfung', options:['Pr\u00fcfung','Gepr\u00fcft','Pr\u00fcfer','Pr\u00fcfen'],
    explanation:'pr\u00fcfen \u2192 die Pr\u00fcfung.' },
  { id:'B2_gr_40', level:'B2', topic:'Nominalization', type:'fill-blank',
    prompt:'Verb: sich entwickeln \u2192 Nomen: die ___',
    answer:'Entwicklung', options:['Entwicklung','Entwickelung','Sichentwicklung','Entwickelt'],
    explanation:'sich entwickeln \u2192 die Entwicklung.' },

  // ── Participle Constructions (5 more) ──
  { id:'B2_gr_41', level:'B2', topic:'Participle Constructions', type:'fill-blank',
    prompt:'Partizip I von "laufen": das ___ Kind',
    answer:'laufende', options:['laufende','gelaufene','laufend','gelaufen'],
    explanation:'Partizip I (Aktiv, gleichzeitig): Infinitiv + d + Endung.' },
  { id:'B2_gr_42', level:'B2', topic:'Participle Constructions', type:'fill-blank',
    prompt:'Partizip II von "kochen": das ___ Wasser',
    answer:'gekochte', options:['gekochte','kochende','kochend','gekocht'],
    explanation:'Partizip II (Passiv, vorzeitig): ge + Stamm + t/en + Endung.' },
  { id:'B2_gr_43', level:'B2', topic:'Participle Constructions', type:'sentence-correction',
    prompt:'Correct: Der Mann, der lacht, ist mein Bruder. (Use Partizip I)',
    answer:'Der lachende Mann ist mein Bruder.',
    explanation:'Partizip I + Nomen ersetzt Relativsatz mit Aktiv.' },
  { id:'B2_gr_44', level:'B2', topic:'Participle Constructions', type:'fill-blank',
    prompt:'Das ___ Buch liegt auf dem Tisch. (lesen - gerade gelesen werdend)',
    answer:'gelesene', options:['gelesene','lesende','lesend','gelesen'],
    explanation:'Partizip II: ein gelesenes Buch = ein Buch, das gelesen wurde.' },
  { id:'B2_gr_45', level:'B2', topic:'Participle Constructions', type:'mcq',
    prompt:'"Die Sch\u00fcler, die arbeiten, sind flei\u00dfig." \u2192 "Die ___ Sch\u00fcler sind flei\u00dfig."',
    answer:'arbeitenden', options:['arbeitenden','gearbeiteten','arbeitend','gearbeitet'],
    explanation:'Partizip I: arbeitend + en (Aktiv, gleichzeitig).' },

  // ── Connectors (5 more) ──
  { id:'B2_gr_46', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'___ es regnet, gehe ich spazieren.',
    answer:'Obwohl', options:['Obwohl','Weil','Wenn','Dass'],
    explanation:'obwohl = although (konzessiv).' },
  { id:'B2_gr_47', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Er lernt viel, ___ er die Pr\u00fcfung bestehen will.',
    answer:'weil', options:['weil','obwohl','trotzdem','damit'],
    explanation:'weil = because (kausal).' },
  { id:'B2_gr_48', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Ich rufe dich an, ___ ich zu Hause bin.',
    answer:'sobald', options:['sobald','bis','w\u00e4hrend','nachdem'],
    explanation:'sobald = as soon as (temporal).' },
  { id:'B2_gr_49', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Sie arbeitet, ___ ihr Mann den Haushalt macht.',
    answer:'w\u00e4hrend', options:['w\u00e4hrend','weil','obwohl','trotzdem'],
    explanation:'w\u00e4hrend = while (temporal/gleichzeitig).' },
  { id:'B2_gr_50', level:'B2', topic:'Connectors', type:'mcq',
    prompt:'___ du fertig bist, gehen wir essen.',
    answer:'Wenn', options:['Wenn','Als','Ob','Wann'],
    explanation:'Wenn = when (wiederholte oder zuk\u00fcnftige Handlung).' },

  // ── N-Deklination (5 more) ──
  { id:'B2_gr_51', level:'B2', topic:'N-Deklination', type:'fill-blank',
    prompt:'Ich sehe ___ (der Student) im H\u00f6rsaal.',
    answer:'den Studenten', options:['den Studenten','der Student','dem Student','des Studenten'],
    explanation:'N-Deklination: schwache maskuline Nomen bekommen -(e)n.' },
  { id:'B2_gr_52', level:'B2', topic:'N-Deklination', type:'fill-blank',
    prompt:'Wir helfen ___ (der Junge).',
    answer:'dem Jungen', options:['dem Jungen','der Junge','den Jungen','des Jungen'],
    explanation:'Dativ: dem + Jungen (N-Deklination).' },
  { id:'B2_gr_53', level:'B2', topic:'N-Deklination', type:'fill-blank',
    prompt:'Das ist das Auto ___ (der Herr).',
    answer:'des Herrn', options:['des Herrn','der Herr','dem Herrn','den Herrn'],
    explanation:'Genitiv: des + Herrn.' },
  { id:'B2_gr_54', level:'B2', topic:'N-Deklination', type:'fill-blank',
    prompt:'Ich habe ___ (der Kollege) eingeladen.',
    answer:'den Kollegen', options:['den Kollegen','der Kollege','dem Kollege','des Kollegen'],
    explanation:'Akkusativ: den + Kollegen.' },
  { id:'B2_gr_55', level:'B2', topic:'N-Deklination', type:'mcq',
    prompt:'Welche Nomen geh\u00f6ren zur N-Deklination?',
    answer:'der Student, der Junge, der Herr', options:['der Student, der Junge, der Herr','die Frau, das Kind, der Tisch','der Mann, der Hund, der Baum','der Lehrer, das Buch, die Schule'],
    explanation:'N-Deklination betrifft bestimmte maskuline Nomen.' },

  // ── Extended Infinitives (5 more) ──
  { id:'B2_gr_56', level:'B2', topic:'Extended Infinitives', type:'fill-blank',
    prompt:'Er geht ins Kino, ___ einen Film ___ sehen.',
    answer:'um zu', options:['um zu','ohne zu','statt zu','damit'],
    explanation:'um...zu = in order to.' },
  { id:'B2_gr_57', level:'B2', topic:'Extended Infinitives', type:'fill-blank',
    prompt:'Er ging zur Party, ___ etwas ___ trinken.',
    answer:'ohne zu', options:['um zu','ohne zu','statt zu','damit'],
    explanation:'ohne...zu = without doing something.' },
  { id:'B2_gr_58', level:'B2', topic:'Extended Infinitives', type:'fill-blank',
    prompt:'___ zu lernen, spielt er Computerspiele.',
    answer:'Statt', options:['Statt','Um','Ohne','Anstatt'],
    explanation:'(An)statt...zu = instead of.' },
  { id:'B2_gr_59', level:'B2', topic:'Extended Infinitives', type:'fill-blank',
    prompt:'Er hat das Buch gekauft, ___ es ___ lesen.',
    answer:'um zu', options:['ohne zu','um zu','statt zu','anstatt zu'],
    explanation:'um...zu gibt den Zweck an.' },
  { id:'B2_gr_60', level:'B2', topic:'Extended Infinitives', type:'sentence-correction',
    prompt:'Correct: Er verlie\u00df das Haus. Er sagte nichts. (Use ohne...zu)',
    answer:'Er verlie\u00df das Haus, ohne etwas zu sagen.',
    explanation:'ohne...zu + Infinitiv.' },

  // ── Future II (5 more) ──
  { id:'B2_gr_61', level:'B2', topic:'Future II', type:'fill-blank',
    prompt:'Bis morgen ___ ich die Arbeit ___ (erledigen - Future II).',
    answer:'werde erledigt haben', options:['werde erledigt haben','habe erledigt','wird erledigt haben','werde erledigen'],
    explanation:'Future II: werden + Partizip II + haben/sein (Vermutung \u00fcber Abgeschlossenes).' },
  { id:'B2_gr_62', level:'B2', topic:'Future II', type:'fill-blank',
    prompt:'Sie ___ das bestimmt ___ (vergessen - Future II).',
    answer:'wird vergessen haben', options:['wird vergessen haben','hat vergessen','vergisst','wird vergessen'],
    explanation:'Future II f\u00fcr Vermutungen \u00fcber die Vergangenheit.' },
  { id:'B2_gr_63', level:'B2', topic:'Future II', type:'fill-blank',
    prompt:'Er ___ wohl schon ___ (ankommen - Future II).',
    answer:'wird angekommen sein', options:['wird angekommen sein','ist angekommen','wird ankommen','kam an'],
    explanation:'Future II mit sein (Bewegungsverben).' },
  { id:'B2_gr_64', level:'B2', topic:'Future II', type:'mcq',
    prompt:'Wann dr\u00fcckt Future II eine Vermutung aus?',
    answer:'Bei Annahmen \u00fcber die Vergangenheit', options:['Bei Annahmen \u00fcber die Vergangenheit','Bei sicheren Tatsachen','Bei Befehlen','Bei W\u00fcnschen'],
    explanation:'Future II wird oft f\u00fcr Vermutungen verwendet: Er wird wohl schon gegessen haben.' },
  { id:'B2_gr_65', level:'B2', topic:'Future II', type:'fill-blank',
    prompt:'Du ___ dich bestimmt ___ (verlaufen - Future II).',
    answer:'wirst verlaufen haben', options:['wirst verlaufen haben','hast verlaufen','verl\u00e4ufst dich','wirst verlaufen'],
    explanation:'Future II: wirst + Partizip II + haben.' },

  // ── Complex Connectors (5 more) ──
  { id:'B2_gr_66', level:'B2', topic:'Complex Connectors', type:'fill-blank',
    prompt:'___ mehr er \u00fcbt, ___ besser wird er.',
    answer:'Je desto', options:['Je desto','Je als','Weil desto','Wenn dann'],
    explanation:'je...desto = the...the (Vergleich).' },
  { id:'B2_gr_67', level:'B2', topic:'Complex Connectors', type:'fill-blank',
    prompt:'Er spricht ___ Deutsch ___ Englisch.',
    answer:'sowohl als auch', options:['sowohl als auch','weder noch','entweder oder','nicht nur sondern auch'],
    explanation:'sowohl...als auch = both...and.' },
  { id:'B2_gr_68', level:'B2', topic:'Complex Connectors', type:'fill-blank',
    prompt:'___ heute ___ morgen kann ich kommen.',
    answer:'Weder noch', options:['Sowohl als auch','Weder noch','Entweder oder','Nicht nur sondern auch'],
    explanation:'weder...noch = neither...nor.' },
  { id:'B2_gr_69', level:'B2', topic:'Complex Connectors', type:'fill-blank',
    prompt:'Er ist ___ intelligent, ___ sehr flei\u00dfig.',
    answer:'nicht nur sondern auch', options:['nicht nur sondern auch','weder noch','sowohl als auch','entweder oder'],
    explanation:'nicht nur...sondern auch = not only...but also.' },
  { id:'B2_gr_70', level:'B2', topic:'Complex Connectors', type:'fill-blank',
    prompt:'___ f\u00e4hrst du, ___ ich fahre.',
    answer:'Entweder oder', options:['Entweder oder','Weder noch','Sowohl als auch','Je desto'],
    explanation:'entweder...oder = either...or.' },

  // ── Subjunctive I (5 more) ──
  { id:'B2_gr_71', level:'B2', topic:'Subjunctive I', type:'fill-blank',
    prompt:'Er sagte, er ___ krank. (sein - Konjunktiv I)',
    answer:'sei', options:['sei','ist','w\u00e4re','war'],
    explanation:'Konjunktiv I f\u00fcr indirekte Rede: er sei.' },
  { id:'B2_gr_72', level:'B2', topic:'Subjunctive I', type:'fill-blank',
    prompt:'Sie behauptete, sie ___ keine Zeit. (haben - KI)',
    answer:'habe', options:['habe','hat','h\u00e4tte','hatte'],
    explanation:'Konjunktiv I: sie habe.' },
  { id:'B2_gr_73', level:'B2', topic:'Subjunctive I', type:'fill-blank',
    prompt:'Der Arzt sagt, die Patienten ___ sich erholen. (k\u00f6nnen - KI)',
    answer:'k\u00f6nnten', options:['k\u00f6nnen','k\u00f6nnten','konnten','k\u00f6nnt'],
    explanation:'Konjunktiv I: k\u00f6nnen \u2192 k\u00f6nnten (da KI = KII bei Modalverben).' },
  { id:'B2_gr_74', level:'B2', topic:'Subjunctive I', type:'fill-blank',
    prompt:'Er sagte, er ___ morgen kommen. (werden - KI)',
    answer:'werde', options:['werde','wird','w\u00fcrde','ward'],
    explanation:'Konjunktiv I Futur: werde + Infinitiv.' },
  { id:'B2_gr_75', level:'B2', topic:'Subjunctive I', type:'mcq',
    prompt:'Wann verwendet man Konjunktiv I?',
    answer:'In der indirekten Rede', options:['In der indirekten Rede','Bei irrealen W\u00fcnschen','Bei H\u00f6flichkeitsformen','Bei Bedingungen'],
    explanation:'Konjunktiv I wird haupts\u00e4chlich f\u00fcr indirekte Rede verwendet.' },

  // ── Modal Verb Meanings Subjective (5) ──
  { id:'B2_gr_76', level:'B2', topic:'Modal Verb Meanings', type:'mcq',
    prompt:'"Er muss zu Hause sein" bedeutet:',
    answer:'Ich bin \u00fcberzeugt, er ist zu Hause.', options:['Ich bin \u00fcberzeugt, er ist zu Hause.','Er hat die Pflicht, zu Hause zu sein.','Vielleicht ist er zu Hause.','Er will zu Hause sein.'],
    explanation:'m\u00fcssen (subjektiv) = hohe Wahrscheinlichkeit (80-90%).' },
  { id:'B2_gr_77', level:'B2', topic:'Modal Verb Meanings', type:'mcq',
    prompt:'"Er kann zu Hause sein" bedeutet:',
    answer:'Es ist m\u00f6glich, dass er zu Hause ist.', options:['Es ist m\u00f6glich, dass er zu Hause ist.','Er hat die F\u00e4higkeit, zu Hause zu sein.','Es ist sicher.','Er m\u00f6chte zu Hause sein.'],
    explanation:'k\u00f6nnen (subjektiv) = m\u00f6gliche Vermutung (30-50%).' },
  { id:'B2_gr_78', level:'B2', topic:'Modal Verb Meanings', type:'fill-blank',
    prompt:'"Das ___ wahr sein!" (Ich kann es kaum glauben.)',
    answer:'kann nicht', options:['kann nicht','muss','darf','mag'],
    explanation:'kann nicht (subjektiv) = das Gegenteil ist sehr wahrscheinlich.' },
  { id:'B2_gr_79', level:'B2', topic:'Modal Verb Meanings', type:'fill-blank',
    prompt:'"Er ___ schon l\u00e4ngst zu Hause sein." (Vermutung)',
    answer:'d\u00fcrfte', options:['d\u00fcrfte','muss','kann','soll'],
    explanation:'d\u00fcrfte (subjektiv) = wahrscheinliche Annahme (60-70%).' },
  { id:'B2_gr_80', level:'B2', topic:'Modal Verb Meanings', type:'mcq',
    prompt:'"Sie soll sehr klug sein" bedeutet:',
    answer:'Man sagt, sie sei sehr klug.', options:['Man sagt, sie sei sehr klug.','Sie ist verpflichtet, klug zu sein.','Sie m\u00f6chte klug sein.','Sie ist sicher klug.'],
    explanation:'sollen (subjektiv) = Behauptung/ Ger\u00fccht von anderen.' },

  // ── Double Connectors (5 more) ──
  { id:'B2_gr_81', level:'B2', topic:'Double Connectors', type:'fill-blank',
    prompt:'___ die Sonne scheint, ___ regnet es.',
    answer:'Bald bald', options:['Bald bald','Je desto','Nicht nur sondern auch','Weder noch'],
    explanation:'bald...bald = sometimes...sometimes.' },
  { id:'B2_gr_82', level:'B2', topic:'Double Connectors', type:'fill-blank',
    prompt:'___ arbeitet sie im B\u00fcro, ___ von zu Hause.',
    answer:'Mal mal', options:['Mal mal','Bald bald','Teils teils','Sowohl als auch'],
    explanation:'mal...mal = alternately / sometimes...sometimes.' },
  { id:'B2_gr_83', level:'B2', topic:'Double Connectors', type:'fill-blank',
    prompt:'___ war die Pr\u00fcfung schwer, ___ war sie fair.',
    answer:'Einerseits andererseits', options:['Einerseits andererseits','Sowohl als auch','Nicht nur sondern auch','Zwar aber'],
    explanation:'einerseits...andererseits = on the one hand...on the other hand.' },
  { id:'B2_gr_84', level:'B2', topic:'Double Connectors', type:'fill-blank',
    prompt:'Die Arbeit war ___ anstrengend, ___ hat sie Spa\u00df gemacht.',
    answer:'zwar aber', options:['zwar aber','sowohl als auch','nicht nur sondern auch','einerseits andererseits'],
    explanation:'zwar...aber = it\'s true that...but.' },
  { id:'B2_gr_85', level:'B2', topic:'Double Connectors', type:'fill-blank',
    prompt:'___ der Aufgabe schwierig, ___ hat er sie gel\u00f6st.',
    answer:'Zwar aber', options:['Zwar aber','Obwohl dennoch','Weil deshalb','Wenn dann'],
    explanation:'zwar...aber verbindet zwei gegens\u00e4tzliche Aussagen.' },

  // ── Genitive Prepositions (5 more) ──
  { id:'B2_gr_86', level:'B2', topic:'Genitive Prepositions', type:'fill-blank',
    prompt:'___ des Regens gehen wir spazieren.',
    answer:'Trotz', options:['Trotz','Wegen','W\u00e4hrend','Au\u00dferhalb'],
    explanation:'trotz + Genitiv = despite.' },
  { id:'B2_gr_87', level:'B2', topic:'Genitive Prepositions', type:'fill-blank',
    prompt:'___ des schlechten Wetters bleiben wir zu Hause.',
    answer:'Wegen', options:['Wegen','Trotz','W\u00e4hrend','Innerhalb'],
    explanation:'wegen + Genitiv = because of.' },
  { id:'B2_gr_88', level:'B2', topic:'Genitive Prepositions', type:'fill-blank',
    prompt:'___ des Krieges sind viele Menschen geflohen.',
    answer:'W\u00e4hrend', options:['W\u00e4hrend','Trotz','Wegen','Au\u00dferhalb'],
    explanation:'w\u00e4hrend + Genitiv = during.' },
  { id:'B2_gr_89', level:'B2', topic:'Genitive Prepositions', type:'fill-blank',
    prompt:'___ der Stadt gibt es viele Parks.',
    answer:'Innerhalb', options:['Innerhalb','Au\u00dferhalb','Oberhalb','Unterhalb'],
    explanation:'innerhalb + Genitiv = within / inside.' },
  { id:'B2_gr_90', level:'B2', topic:'Genitive Prepositions', type:'fill-blank',
    prompt:'___ des Stadtzentrums ist es ruhiger.',
    answer:'Au\u00dferhalb', options:['Au\u00dferhalb','Innerhalb','Oberhalb','Unterhalb'],
    explanation:'au\u00dferhalb + Genitiv = outside of.' },

  // ── Verb Fixed Prepositions (5 more) ──
  { id:'B2_gr_91', level:'B2', topic:'Verb Fixed Prepositions', type:'fill-blank',
    prompt:'Ich warte ___ meinen Freund.',
    answer:'auf', options:['auf','f\u00fcr','um','an'],
    explanation:'warten auf + Akkusativ.' },
  { id:'B2_gr_92', level:'B2', topic:'Verb Fixed Prepositions', type:'fill-blank',
    prompt:'Sie interessiert sich ___ Kunst.',
    answer:'f\u00fcr', options:['f\u00fcr','an','auf','von'],
    explanation:'sich interessieren f\u00fcr + Akkusativ.' },
  { id:'B2_gr_93', level:'B2', topic:'Verb Fixed Prepositions', type:'fill-blank',
    prompt:'Er denkt ___ die Zukunft.',
    answer:'an', options:['an','auf','von','\u00fcber'],
    explanation:'denken an + Akkusativ.' },
  { id:'B2_gr_94', level:'B2', topic:'Verb Fixed Prepositions', type:'fill-blank',
    prompt:'Sie freut sich ___ ihren Geburtstag.',
    answer:'auf', options:['auf','\u00fcber','an','von'],
    explanation:'sich freuen auf (Zukunft) + Akkusativ.' },
  { id:'B2_gr_95', level:'B2', topic:'Verb Fixed Prepositions', type:'fill-blank',
    prompt:'Er bedankt sich ___ die Hilfe.',
    answer:'f\u00fcr', options:['f\u00fcr','bei','mit','an'],
    explanation:'sich bedanken f\u00fcr + Akkusativ.' },

  // ── Complex Passive (5 more) ──
  { id:'B2_gr_96', level:'B2', topic:'Complex Passive', type:'fill-blank',
    prompt:'Der Brief ___ gestern ___ geschrieben ___ (m\u00fcssen - Perfekt Passiv).',
    answer:'hat werden m\u00fcssen', options:['hat geschrieben werden m\u00fcssen','hat werden m\u00fcssen','muss geschrieben werden','wurde geschrieben'],
    explanation:'Modalverb Perfekt Passiv: hat + Partizip II + werden + m\u00fcssen.' },
  { id:'B2_gr_97', level:'B2', topic:'Complex Passive', type:'fill-blank',
    prompt:'Das ___ nicht ___ gemacht ___ (d\u00fcrfen - Perfekt Passiv).',
    answer:'hat werden d\u00fcrfen', options:['hat werden d\u00fcrfen','darf nicht gemacht werden','wurde nicht gemacht','hat nicht gemacht'],
    explanation:'Modalverb Perfekt Passiv: hat + Partizip II + werden + d\u00fcrfen.' },
  { id:'B2_gr_98', level:'B2', topic:'Complex Passive', type:'mcq',
    prompt:'"Die G\u00e4ste \/ begr\u00fc\u00dfen \/ werden \/ k\u00f6nnen \/ haben" - Richtige Reihenfolge Perfekt Passiv mit Modal?',
    answer:'haben begr\u00fc\u00dft werden k\u00f6nnen', options:['haben begr\u00fc\u00dft werden k\u00f6nnen','k\u00f6nnen begr\u00fc\u00dft haben','werden begr\u00fc\u00dft haben k\u00f6nnen','haben k\u00f6nnen begr\u00fc\u00dft werden'],
    explanation:'Perfekt Passiv mit Modal: haben + Partizip II + werden + Modalverb.' },
  { id:'B2_gr_99', level:'B2', topic:'Complex Passive', type:'fill-blank',
    prompt:'Der Termin ___ verschoben ___ (m\u00fcssen - worden + m\u00fcssen Ersatzinfinitiv).',
    answer:'hat werden m\u00fcssen', options:['hat werden m\u00fcssen','ist verschoben worden','muss verschoben werden','wurde verschoben'],
    explanation:'Ersatzinfinitiv bei Modal im Perfekt: hat + Partizip II + werden + Modal.' },
  { id:'B2_gr_100', level:'B2', topic:'Complex Passive', type:'fill-blank',
    prompt:'Die Entscheidung ___ ___ werden m\u00fcssen (sollen - Perfekt).',
    answer:'hat getroffen', options:['hat getroffen','ist getroffen','wurde getroffen','wird getroffen'],
    explanation:'sollen Passiv Perfekt: hat + Partizip II + werden + sollen (Ersatzinfinitiv).' },

  // ── Indirect Questions (10) ──
  { id:'B2_gr_101', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Ich m\u00f6chte wissen, ___ er kommt.',
    answer:'ob', options:['ob','wann','wer','was'],
    explanation:'ob f\u00fcr indirekte Ja\/Nein-Fragen.' },
  { id:'B2_gr_102', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Kannst du mir sagen, ___ der Zug abf\u00e4hrt?',
    answer:'wann', options:['wann','ob','dass','weil'],
    explanation:'Indirekte W-Frage: Fragewort bleibt, Verb ans Ende.' },
  { id:'B2_gr_103', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Sie fragte, ___ ich schon gegessen habe.',
    answer:'ob', options:['ob','was','dass','warum'],
    explanation:'ob in indirekten Ja\/Nein-Fragen.' },
  { id:'B2_gr_104', level:'B2', topic:'Indirect Questions', type:'mcq',
    prompt:'Direkt: "Wo wohnst du?" \u2192 Indirekt:',
    answer:'Er fragt, wo ich wohne.', options:['Er fragt, wo ich wohne.','Er fragt, wo wohnst du.','Er fragt, ob ich wohne.','Er fragt, dass ich wohne.'],
    explanation:'Indirekte Frage: Verb am Ende, du \u2192 ich.' },
  { id:'B2_gr_105', level:'B2', topic:'Indirect Questions', type:'sentence-correction',
    prompt:'Correct: "Er fragte: Kommst du mit?" \u2192 Indirekte Rede',
    answer:'Er fragte, ob ich mitkomme.',
    explanation:'Indirekte Ja\/Nein-Frage mit ob.' },
  { id:'B2_gr_106', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Wei\u00dft du, ___ das gemacht hat?',
    answer:'wer', options:['wer','wen','wem','wessen'],
    explanation:'wer (Nominativ) f\u00fcr die Person, die handelt.' },
  { id:'B2_gr_107', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Ich will wissen, ___ sie sich trifft.',
    answer:'mit wem', options:['mit wem','wer','wessen','wen'],
    explanation:'mit + Dativ: mit wem.' },
  { id:'B2_gr_108', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Erkl\u00e4r mir, ___ das funktioniert.',
    answer:'wie', options:['wie','was','wer','wann'],
    explanation:'wie f\u00fcr die Art und Weise.' },
  { id:'B2_gr_109', level:'B2', topic:'Indirect Questions', type:'fill-blank',
    prompt:'Niemand wei\u00df, ___ es passiert ist.',
    answer:'warum', options:['warum','ob','wann','wo'],
    explanation:'warum f\u00fcr den Grund.' },
  { id:'B2_gr_110', level:'B2', topic:'Indirect Questions', type:'mcq',
    prompt:'"Hast du Hunger?" (indirekt mit "Er fragt")',
    answer:'Er fragt, ob ich Hunger habe.', options:['Er fragt, ob ich Hunger habe.','Er fragt, dass ich Hunger habe.','Er fragt, was ich Hunger habe.','Er fragt, wann ich Hunger habe.'],
    explanation:'ob f\u00fcr Ja\/Nein-Fragen in indirekter Rede.' },

  // ── Relative Clauses with Prepositions (10) ──
  { id:'B2_gr_111', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Der Mann, ___ ich dir erz\u00e4hlt habe, kommt heute.',
    answer:'von dem', options:['von dem','von der','von den','von'],
    explanation:'Relativsatz mit Pr\u00e4position: Pr\u00e4position + Relativpronomen im passenden Kasus.' },
  { id:'B2_gr_112', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Das ist die Freundin, ___ ich zusammen wohne.',
    answer:'mit der', options:['mit der','mit dem','mit die','mit denen'],
    explanation:'zusammenwohnen mit + Dativ.' },
  { id:'B2_gr_113', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Firma, ___ er arbeitet, ist gro\u00df.',
    answer:'bei der', options:['bei der','bei dem','bei die','bei das'],
    explanation:'arbeiten bei + Dativ.' },
  { id:'B2_gr_114', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Der Stift, ___ ich schreibe, ist neu.',
    answer:'mit dem', options:['mit dem','mit der','mit die','mit das'],
    explanation:'schreiben mit + Dativ.' },
  { id:'B2_gr_115', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Sache, ___ es geht, ist wichtig.',
    answer:'um die', options:['um die','um der','um das','um den'],
    explanation:'es geht um + Akkusativ.' },
  { id:'B2_gr_116', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Das Problem, ___ ich mich k\u00fcmmern muss, ist gro\u00df.',
    answer:'um das', options:['um das','um den','um die','um der'],
    explanation:'sich k\u00fcmmern um + Akkusativ.' },
  { id:'B2_gr_117', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Der Kollege, ___ ich mich freue, besucht uns.',
    answer:'auf den', options:['auf den','auf der','auf das','auf die'],
    explanation:'sich freuen auf + Akkusativ.' },
  { id:'B2_gr_118', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Der Kurs, ___ ich teilnehme, ist ausgebucht.',
    answer:'an dem', options:['an dem','an den','an die','an der'],
    explanation:'teilnehmen an + Dativ.' },
  { id:'B2_gr_119', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Idee, ___ ich nachdenke, ist gut.',
    answer:'\u00fcber die', options:['\u00fcber die','\u00fcber der','\u00fcber das','\u00fcber den'],
    explanation:'nachdenken \u00fcber + Akkusativ.' },
  { id:'B2_gr_120', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Frau, ___ ich mich bedanke, ist meine Nachbarin.',
    answer:'bei der', options:['bei der','bei dem','bei die','bei das'],
    explanation:'sich bedanken bei + Dativ.' },

  // ── Subjunctive II (past, polite requests, unreal conditions) (15) ──
  { id:'B2_gr_121', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich Zeit ___, w\u00fcrde ich verreisen. (haben - KII)',
    answer:'h\u00e4tte', options:['h\u00e4tte','habe','hatte','haben w\u00fcrde'],
    explanation:'Konjunktiv II von haben: h\u00e4tte.' },
  { id:'B2_gr_122', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich mehr Geld ___, w\u00fcrde ich ein Haus kaufen.',
    answer:'h\u00e4tte', options:['h\u00e4tte','habe','hatte','haben w\u00fcrde'],
    explanation:'Irrealer Bedingungssatz: wenn + KII, w\u00fcrde + Infinitiv.' },
  { id:'B2_gr_123', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Ich w\u00fcrde gern mitkommen, wenn ich ___ (d\u00fcrfen - KII).',
    answer:'d\u00fcrfte', options:['d\u00fcrfte','darf','durfte','d\u00fcrfen w\u00fcrde'],
    explanation:'Konjunktiv II von d\u00fcrfen: d\u00fcrfte.' },
  { id:'B2_gr_124', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'___ ich bitte vorbei? (d\u00fcrfen - h\u00f6flich)',
    answer:'D\u00fcrfte', options:['D\u00fcrfte','Darf','Durfte','D\u00fcrfe'],
    explanation:'KII f\u00fcr h\u00f6fliche Fragen: D\u00fcrfte ich...' },
  { id:'B2_gr_125', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn er fr\u00fcher gekommen ___, h\u00e4tte er den Zug erreicht. (sein - KII)',
    answer:'w\u00e4re', options:['w\u00e4re','ist','war','sei'],
    explanation:'KII Vergangenheit: w\u00e4re + Partizip II (Irrealis).' },
  { id:'B2_gr_126', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich das gewusst ___, h\u00e4tte ich anders gehandelt.',
    answer:'h\u00e4tte', options:['h\u00e4tte','habe','hatte','w\u00fcrde'],
    explanation:'KII Plusquamperfekt: h\u00e4tte + Partizip II.' },
  { id:'B2_gr_127', level:'B2', topic:'Subjunctive II', type:'mcq',
    prompt:'"K\u00f6nnten Sie mir bitte helfen?" - Welche Funktion hat KII hier?',
    answer:'H\u00f6flichkeit', options:['H\u00f6flichkeit','Irrealer Wunsch','Indirekte Rede','Vergangenheit'],
    explanation:'KII mit Modalverben f\u00fcr h\u00f6fliche Bitten.' },
  { id:'B2_gr_128', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'___ ich doch mehr Zeit! (haben - Wunsch)',
    answer:'H\u00e4tte', options:['H\u00e4tte','Habe','Hatte','Haben w\u00fcrde'],
    explanation:'Irrealer Wunsch: H\u00e4tte ich doch...' },
  { id:'B2_gr_129', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich ein Vogel ___, w\u00fcrde ich zu dir fliegen.',
    answer:'w\u00e4re', options:['w\u00e4re','bin','war','sei'],
    explanation:'KII von sein: w\u00e4re (irrealer Vergleich).' },
  { id:'B2_gr_130', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Es ___ besser, wenn du morgen kommst. (sein - KII)',
    answer:'w\u00e4re', options:['w\u00e4re','ist','war','sei'],
    explanation:'H\u00f6flicher Vorschlag mit KII.' },
  { id:'B2_gr_131', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'An deiner Stelle ___ ich nicht so sp\u00e4t kommen.',
    answer:'w\u00fcrde', options:['w\u00fcrde','werde','will','wollte'],
    explanation:'An deiner Stelle w\u00fcrde ich... (Ratschlag).' },
  { id:'B2_gr_132', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Sie tat so, als ob sie nichts ___ (wissen - KII).',
    answer:'w\u00fcsste', options:['w\u00fcsste','wei\u00df','wusste','wissen w\u00fcrde'],
    explanation:'als ob + KII (irrealer Vergleich).' },
  { id:'B2_gr_133', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich du ___, w\u00fcrde ich den Job annehmen.',
    answer:'w\u00e4re', options:['w\u00e4re','bin','war','sei'],
    explanation:'Wenn ich du w\u00e4re (feste Wendung).' },
  { id:'B2_gr_134', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Er ___ gern, aber er kann nicht. (wollen - KII)',
    answer:'w\u00fcrde', options:['w\u00fcrde','will','wollte','mag'],
    explanation:'w\u00fcrde gern = would like to.' },
  { id:'B2_gr_135', level:'B2', topic:'Subjunctive II', type:'mcq',
    prompt:'"Ich h\u00e4tte gern ein Glas Wasser" ist ___',
    answer:'h\u00f6fliche Bitte', options:['h\u00f6fliche Bitte','Vergangenheit','Befehl','Vermutung'],
    explanation:'h\u00e4tte gern = h\u00f6fliche Bitte im KII.' },

  // ── Adjective Declension (indefinite articles) (10) ──
  { id:'B2_gr_136', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Er hat ein ___ Haus gekauft. (gro\u00df)',
    answer:'gro\u00dfes', options:['gro\u00dfes','gro\u00dfen','gro\u00dfe','gro\u00dfer'],
    explanation:'Nach unbestimmtem Artikel, Neutrum Nominativ: ein gro\u00dfes Haus.' },
  { id:'B2_gr_137', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Ich suche eine ___ Wohnung. (neu)',
    answer:'neue', options:['neue','neuen','neuer','neues'],
    explanation:'Nach unbestimmtem Artikel, Femininum Akkusativ: eine neue Wohnung.' },
  { id:'B2_gr_138', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Das ist ein ___ Tag. (sch\u00f6n)',
    answer:'sch\u00f6ner', options:['sch\u00f6ner','sch\u00f6nen','sch\u00f6ne','sch\u00f6nes'],
    explanation:'Nach unbestimmtem Artikel, Maskulinum Nominativ: ein sch\u00f6ner Tag.' },
  { id:'B2_gr_139', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Sie trinkt ein ___ Getr\u00e4nk. (kalt)',
    answer:'kaltes', options:['kaltes','kalten','kalte','kalter'],
    explanation:'Neutrum Akkusativ: ein kaltes Getr\u00e4nk.' },
  { id:'B2_gr_140', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Der ___ (gro\u00df) Hund geh\u00f6rt mir.',
    answer:'gro\u00dfe', options:['gro\u00dfe','gro\u00dfen','gro\u00dfer','gro\u00dfes'],
    explanation:'Nach bestimmtem Artikel, Maskulinum Nominativ: der gro\u00dfe Hund.' },
  { id:'B2_gr_141', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Ich helfe dem ___ Mann. (alt)',
    answer:'alten', options:['alten','alte','alter','altes'],
    explanation:'Dativ Maskulinum: dem alten Mann.' },
  { id:'B2_gr_142', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Mit ___ (neu) Freunden trifft man sich gern.',
    answer:'neuen', options:['neuen','neue','neuer','neues'],
    explanation:'Dativ Plural: mit neuen Freunden.' },
  { id:'B2_gr_143', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Sie wohnt in einer ___ Stra\u00dfe. (ruhig)',
    answer:'ruhigen', options:['ruhigen','ruhige','ruhiger','ruhiges'],
    explanation:'Dativ Femininum (nach einer): in einer ruhigen Stra\u00dfe.' },
  { id:'B2_gr_144', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Ohne ___ (sauber) Wasser kann man nicht leben.',
    answer:'sauberes', options:['sauberes','sauberen','saubere','sauberer'],
    explanation:'Ohne (ohne Artikel) + Neutrum Akkusativ: sauberes Wasser.' },
  { id:'B2_gr_145', level:'B2', topic:'Adjective Declension', type:'mcq',
    prompt:'Welche Endung ist korrekt? "Sie mag ___ Filme." (gut)',
    answer:'gute', options:['gute','guten','guter','gutes'],
    explanation:'Nach keinem Artikel, Plural Akkusativ: gute Filme.' },

  // ── Two-way Prepositions (10) ──
  { id:'B2_gr_146', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Das Buch liegt ___ dem Tisch.',
    answer:'auf', options:['auf','in','unter','neben'],
    explanation:'auf + Dativ (Position).' },
  { id:'B2_gr_147', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Er legt das Buch ___ den Tisch.',
    answer:'auf', options:['auf','in','unter','neben'],
    explanation:'auf + Akkusativ (Richtung).' },
  { id:'B2_gr_148', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Die Katze schl\u00e4ft ___ dem Bett.',
    answer:'unter', options:['unter','auf','neben','zwischen'],
    explanation:'unter + Dativ (wo? = Position).' },
  { id:'B2_gr_149', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Die Katze kriecht ___ das Bett.',
    answer:'unter', options:['unter','auf','neben','in'],
    explanation:'unter + Akkusativ (wohin? = Richtung).' },
  { id:'B2_gr_150', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Er steht ___ der T\u00fcr.',
    answer:'vor', options:['vor','hinter','neben','zwischen'],
    explanation:'vor + Dativ (Position).' },
  { id:'B2_gr_151', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Er stellt sich ___ die T\u00fcr.',
    answer:'vor', options:['vor','hinter','neben','zwischen'],
    explanation:'vor + Akkusativ (Richtung).' },
  { id:'B2_gr_152', level:'B2', topic:'Two-way Prepositions', type:'mcq',
    prompt:'Wann benutzt man Dativ bei Wechselpr\u00e4positionen?',
    answer:'Bei Position (wo?)', options:['Bei Position (wo?)','Bei Richtung (wohin?)','Bei Zeitangaben','Bei Genitiv'],
    explanation:'Dativ = Position, Akkusativ = Richtung.' },
  { id:'B2_gr_153', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Die Schl\u00fcssel liegen ___ dem Schrank.',
    answer:'zwischen', options:['zwischen','in','auf','neben'],
    explanation:'zwischen + Dativ (Position zwischen mehreren Dingen).' },
  { id:'B2_gr_154', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Er stellt das Regal ___ die Wand.',
    answer:'an', options:['an','auf','in','neben'],
    explanation:'an + Akkusativ (Richtung gegen eine vertikale Fl\u00e4che).' },
  { id:'B2_gr_155', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Das Bild h\u00e4ngt ___ der Wand.',
    answer:'an', options:['an','auf','in','neben'],
    explanation:'an + Dativ (Position an der Wand).' },

  // ── Prepositional Adverbs (da(r)+preposition) (10) ──
  { id:'B2_gr_156', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Ich warte auf die Antwort. \u2192 Ich warte ___.',
    answer:'darauf', options:['darauf','dar\u00fcber','daran','damit'],
    explanation:'da + Pr\u00e4position (auf) = darauf (r bei Vokal).' },
  { id:'B2_gr_157', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Er denkt an die Reise. \u2192 Er denkt ___.',
    answer:'daran', options:['daran','darauf','dadurch','davon'],
    explanation:'da + an = daran.' },
  { id:'B2_gr_158', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Sie freut sich auf die Ferien. \u2192 Sie freut sich ___.',
    answer:'darauf', options:['darauf','davon','dadurch','daran'],
    explanation:'da + auf = darauf (r wegen Vokal).' },
  { id:'B2_gr_159', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Er interessiert sich f\u00fcr Kunst. \u2192 Er interessiert sich ___.',
    answer:'daf\u00fcr', options:['daf\u00fcr','darauf','davon','darunter'],
    explanation:'da + f\u00fcr = daf\u00fcr.' },
  { id:'B2_gr_160', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Womit besch\u00e4ftigst du dich? \u2192 Ich besch\u00e4ftige mich ___.',
    answer:'damit', options:['damit','dadurch','danach','davon'],
    explanation:'Fragewort wo(r) + Pr\u00e4position = Antwort da(r) + Pr\u00e4position.' },
  { id:'B2_gr_161', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Er hat ___ gearbeitet. (an dem Projekt)',
    answer:'daran', options:['daran','darauf','davon','dadurch'],
    explanation:'an einem Projekt arbeiten \u2192 daran arbeiten.' },
  { id:'B2_gr_162', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Sie hat ___ getr\u00e4umt. (von der Reise)',
    answer:'davon', options:['davon','daran','darauf','daf\u00fcr'],
    explanation:'von etwas tr\u00e4umen \u2192 davon tr\u00e4umen.' },
  { id:'B2_gr_163', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'___ hast du das erfahren? (durch wen)',
    answer:'Wodurch', options:['Wodurch','Wof\u00fcr','Woran','Womit'],
    explanation:'Wo(r) + Pr\u00e4position = Frage nach Sachen.' },
  { id:'B2_gr_164', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'___ denkst du? (an was)',
    answer:'Woran', options:['Woran','Wof\u00fcr','Womit','Wodurch'],
    explanation:'Woran denkst du? = What are you thinking about?' },
  { id:'B2_gr_165', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Er freut sich ___ (auf die \u00dcberraschung).',
    answer:'darauf', options:['darauf','dar\u00fcber','daran','dadurch'],
    explanation:'sich freuen auf + Akk \u2192 sich darauf freuen.' },

  // ── Temporal Subclauses (10) ──
  { id:'B2_gr_166', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ er ankam, waren alle schon da. (Vorzeitigkeit)',
    answer:'Als', options:['Als','Wenn','W\u00e4hrend','Nachdem'],
    explanation:'als f\u00fcr einmalige Handlung in der Vergangenheit.' },
  { id:'B2_gr_167', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ ich klein war, habe ich oft im Park gespielt.',
    answer:'Als', options:['Als','Wenn','W\u00e4hrend','Seitdem'],
    explanation:'als f\u00fcr Zustand in der Vergangenheit.' },
  { id:'B2_gr_168', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ ich Zeit habe, lese ich gern.',
    answer:'Wenn', options:['Wenn','Als','W\u00e4hrend','Bevor'],
    explanation:'wenn = immer wenn (Wiederholung) oder in der Zukunft.' },
  { id:'B2_gr_169', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ er kocht, h\u00f6rt er Musik.',
    answer:'W\u00e4hrend', options:['W\u00e4hrend','Als','Wenn','Nachdem'],
    explanation:'w\u00e4hrend = while (gleichzeitig).' },
  { id:'B2_gr_170', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ er gegessen hatte, ging er spazieren.',
    answer:'Nachdem', options:['Nachdem','Bevor','Als','W\u00e4hrend'],
    explanation:'nachdem = after (Vorzeitigkeit: Plusquamperfekt).' },
  { id:'B2_gr_171', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ du gehst, musst du aufr\u00e4umen.',
    answer:'Bevor', options:['Bevor','Nachdem','Wenn','Bis'],
    explanation:'bevor = before (Nachzeitigkeit).' },
  { id:'B2_gr_172', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'Ich warte, ___ du fertig bist.',
    answer:'bis', options:['bis','seitdem','w\u00e4hrend','nachdem'],
    explanation:'bis = until.' },
  { id:'B2_gr_173', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ ich in Berlin wohne, f\u00fchle ich mich wohl.',
    answer:'Seitdem', options:['Seitdem','Bis','W\u00e4hrend','Nachdem'],
    explanation:'seitdem = since (beginnend in der Vergangenheit bis jetzt).' },
  { id:'B2_gr_174', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ ich das Studium abgeschlossen hatte, suchte ich einen Job.',
    answer:'Nachdem', options:['Nachdem','Bevor','Als','W\u00e4hrend'],
    explanation:'nachdem + Plusquamperfekt f\u00fcr Vorzeitigkeit.' },
  { id:'B2_gr_175', level:'B2', topic:'Temporal Subclauses', type:'mcq',
    prompt:'"Wenn ich in Berlin bin" - Das bezieht sich auf...',
    answer:'Wiederholte oder zuk\u00fcnftige Handlungen', options:['Einmalige Vergangenheit','Wiederholte oder zuk\u00fcnftige Handlungen','Gleichzeitige Handlungen','Abgeschlossene Vorzeitigkeit'],
    explanation:'wenn = immer wenn (Wiederholung) oder futurisch.' },

  // ── Conditional Clauses (wenn, falls) (10) ──
  { id:'B2_gr_176', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'___ du morgen Zeit hast, k\u00f6nnen wir uns treffen.',
    answer:'Wenn', options:['Wenn','Falls','Ob','Dass'],
    explanation:'wenn = wenn (Bedingung, h\u00f6here Wahrscheinlichkeit).' },
  { id:'B2_gr_177', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'___ es regnet, bleiben wir zu Hause.',
    answer:'Falls', options:['Falls','Wenn','Ob','Weil'],
    explanation:'falls = in case (m\u00f6glicher Fall, etwas weniger sicher als wenn).' },
  { id:'B2_gr_178', level:'B2', topic:'Conditional Clauses', type:'mcq',
    prompt:'Was ist der Unterschied zwischen "wenn" und "falls"?',
    answer:'falls ist unsicherer als wenn', options:['falls ist unsicherer als wenn','wenn ist unsicherer','beide sind gleich','falls bedeutet trotzdem'],
    explanation:'wenn = wahrscheinlich, falls = m\u00f6glich aber unsicher.' },
  { id:'B2_gr_179', level:'B2', topic:'Conditional Clauses', type:'sentence-correction',
    prompt:'Correct: Wenn du krank bist, musst du zum Arzt gehen. (Begin with subclause)',
    answer:'Wenn du krank bist, musst du zum Arzt gehen.',
    explanation:'Satzanfang mit subclause: Verb im Hauptsatz beginnt nach dem Komma.' },
  { id:'B2_gr_180', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'___ sich das Wetter bessert, spielen wir Fu\u00dfball.',
    answer:'Falls', options:['Falls','Wenn','Obwohl','Weil'],
    explanation:'falls = conditional, unsicher.' },
  { id:'B2_gr_181', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'___ es m\u00f6glich ist, komme ich morgen vorbei.',
    answer:'Falls', options:['Falls','Wenn','Ob','Dass'],
    explanation:'Falls es m\u00f6glich ist = If it\u0027s possible.' },
  { id:'B2_gr_182', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'___ du Hilfe brauchst, ruf mich an.',
    answer:'Wenn', options:['Wenn','Falls','Obwohl','Trotzdem'],
    explanation:'Sowohl wenn als auch falls sind hier m\u00f6glich.' },
  { id:'B2_gr_183', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'Er hilft dir, ___ du ihn darum bittest.',
    answer:'wenn', options:['wenn','falls','ob','dass'],
    explanation:'wenn = wenn (Bedingung).' },
  { id:'B2_gr_184', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'Nur ___ du flei\u00dfig bist, wirst du bestehen.',
    answer:'wenn', options:['wenn','falls','ob','dass'],
    explanation:'Nur wenn = only if (Einschr\u00e4nkung).' },
  { id:'B2_gr_185', level:'B2', topic:'Conditional Clauses', type:'fill-blank',
    prompt:'______ es notwendig ist, k\u00f6nnen wir den Termin verschieben.',
    answer:'Falls', options:['Falls','Wenn','Obwohl','Weil'],
    explanation:'Falls = falls, wenn (A conditional clause).' },

  // ── Concessive Clauses (obwohl, trotzdem) (5) ──
  { id:'B2_gr_186', level:'B2', topic:'Concessive Clauses', type:'fill-blank',
    prompt:'___ es kalt ist, geht er ohne Jacke raus.',
    answer:'Obwohl', options:['Obwohl','Trotzdem','Weil','Deshalb'],
    explanation:'obwohl = although (Nebensatz).' },
  { id:'B2_gr_187', level:'B2', topic:'Concessive Clauses', type:'fill-blank',
    prompt:'Es ist kalt. Er geht ___ ohne Jacke raus.',
    answer:'trotzdem', options:['trotzdem','obwohl','weil','deshalb'],
    explanation:'trotzdem = nevertheless (Hauptsatz).' },
  { id:'B2_gr_188', level:'B2', topic:'Concessive Clauses', type:'mcq',
    prompt:'"Obwohl" leitet einen ___ ein.',
    answer:'Nebensatz', options:['Nebensatz','Hauptsatz','Infinitivsatz','Fragesatz'],
    explanation:'obwohl + Nebensatz (Verb am Ende).' },
  { id:'B2_gr_189', level:'B2', topic:'Concessive Clauses', type:'fill-blank',
    prompt:'___ er m\u00fcde war, arbeitete er weiter.',
    answer:'Obwohl', options:['Obwohl','Trotz','Wegen','Deshalb'],
    explanation:'obwohl (konzessiv).' },
  { id:'B2_gr_190', level:'B2', topic:'Concessive Clauses', type:'fill-blank',
    prompt:'Sie kaufte das Kleid, ___ es teuer war.',
    answer:'obwohl', options:['obwohl','trotzdem','weil','denn'],
    explanation:'obwohl + Nebensatz.' },

  // ── Causative Clauses (weil, da, n\u00e4mlich) (5) ──
  { id:'B2_gr_191', level:'B2', topic:'Causative Clauses', type:'fill-blank',
    prompt:'Er kommt nicht, ___ er krank ist.',
    answer:'weil', options:['weil','da','denn','n\u00e4mlich'],
    explanation:'weil = because (Nebensatz, Verb am Ende).' },
  { id:'B2_gr_192', level:'B2', topic:'Causative Clauses', type:'fill-blank',
    prompt:'___ er noch jung ist, hat er viel Energie.',
    answer:'Da', options:['Da','Weil','Denn','Obwohl'],
    explanation:'da = since (bekannter Grund, oft am Satzanfang).' },
  { id:'B2_gr_193', level:'B2', topic:'Causative Clauses', type:'fill-blank',
    prompt:'Er hat den Zug verpasst, ___ er zu sp\u00e4t losging.',
    answer:'weil', options:['weil','denn','da','n\u00e4mlich'],
    explanation:'weil (Nebensatz).' },
  { id:'B2_gr_194', level:'B2', topic:'Causative Clauses', type:'fill-blank',
    prompt:'Er ist m\u00fcde. Er hat ___ lange gearbeitet.',
    answer:'n\u00e4mlich', options:['n\u00e4mlich','weil','da','denn'],
    explanation:'n\u00e4mlich = namely\/because (nachgestellte Erkl\u00e4rung).' },
  { id:'B2_gr_195', level:'B2', topic:'Causative Clauses', type:'mcq',
    prompt:'"Denn" steht im ___ und Verb in Position ___',
    answer:'Hauptsatz, Position 2', options:['Hauptsatz, Position 2','Nebensatz, Ende','Hauptsatz, Ende','Nebensatz, Position 2'],
    explanation:'denn = Hauptsatz (Verb bleibt auf Position 2).' },

  // ── Final Clauses (damit, um...zu) (5) ──
  { id:'B2_gr_196', level:'B2', topic:'Final Clauses', type:'fill-blank',
    prompt:'Er lernt Deutsch, ___ er in Deutschland studieren kann.',
    answer:'damit', options:['damit','um zu','weil','dass'],
    explanation:'damit = so that ( Finalsatz, verschiedene Subjekte).' },
  { id:'B2_gr_197', level:'B2', topic:'Final Clauses', type:'fill-blank',
    prompt:'Sie geht zur Uni, ___ zu studieren.',
    answer:'um', options:['um','damit','weil','f\u00fcr'],
    explanation:'um...zu + Infinitiv (gleiches Subjekt).' },
  { id:'B2_gr_198', level:'B2', topic:'Final Clauses', type:'fill-blank',
    prompt:'Ich schreibe es auf, ___ ich es nicht vergesse.',
    answer:'damit', options:['damit','um zu','weil','dass'],
    explanation:'damit = so that (verschiedene Subjekte: ich schreibe, ich vergesse nicht).' },
  { id:'B2_gr_199', level:'B2', topic:'Final Clauses', type:'fill-blank',
    prompt:'___ den Job zu bekommen, m\u00fcssen Sie sich gut vorbereiten.',
    answer:'Um', options:['Um','Damit','Weil','Durch'],
    explanation:'Um...zu am Satzanfang (gleiches Subjekt).' },
  { id:'B2_gr_200', level:'B2', topic:'Final Clauses', type:'mcq',
    prompt:'Wann benutzt man "um...zu" und wann "damit"?',
    answer:'um...zu bei gleichem Subjekt, damit bei verschiedenen', options:['um...zu bei gleichem Subjekt, damit bei verschiedenen','um...zu bei verschiedenen, damit bei gleichem','beide sind immer austauschbar','damit ist formeller'],
    explanation:'Gleiches Subjekt: um...zu. Verschiedene Subjekte: damit.' },

  // ── Consecutive Clauses (so...dass, sodass) (5) ──
  { id:'B2_gr_201', level:'B2', topic:'Consecutive Clauses', type:'fill-blank',
    prompt:'Er war ___ m\u00fcde, dass er einschlief.',
    answer:'so', options:['so','sehr','zu','viel'],
    explanation:'so...dass = so...that (Konsekutivsatz).' },
  { id:'B2_gr_202', level:'B2', topic:'Consecutive Clauses', type:'fill-blank',
    prompt:'Es regnete stark, ___ das Spiel abgesagt wurde.',
    answer:'sodass', options:['sodass','weil','obwohl','damit'],
    explanation:'sodass = so that (als Ergebnis).' },
  { id:'B2_gr_203', level:'B2', topic:'Consecutive Clauses', type:'fill-blank',
    prompt:'Sie hatte ___ viel Arbeit, dass sie am Wochenende arbeiten musste.',
    answer:'so', options:['so','zu','viel','sehr'],
    explanation:'so viel + Nomen... dass.' },
  { id:'B2_gr_204', level:'B2', topic:'Consecutive Clauses', type:'mcq',
    prompt:'"Die Pr\u00fcfung war so schwer, dass viele durchgefallen sind." Das dr\u00fcckt ___ aus.',
    answer:'eine Folge', options:['eine Folge','einen Grund','einen Zweck','einen Gegensatz'],
    explanation:'Konsekutivsatz: so...dass dr\u00fcckt die Folge aus.' },
  { id:'B2_gr_205', level:'B2', topic:'Consecutive Clauses', type:'sentence-correction',
    prompt:'Correct: Er rannte schnell. Er gewann das Rennen. (Use sodass)',
    answer:'Er rannte schnell, sodass er das Rennen gewann.',
    explanation:'sodass verbindet Ursache und Folge.' },

  // ── Relative Pronouns Genitive (5) ──
  { id:'B2_gr_206', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Der Mann, ___ Auto gestohlen wurde, rief die Polizei.',
    answer:'dessen', options:['dessen','deren','dem','den'],
    explanation:'dessen = whose (Maskulinum\/Neutrum Genitiv).' },
  { id:'B2_gr_207', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Frau, ___ Tochter \u00c4rztin ist, lebt in Hamburg.',
    answer:'deren', options:['deren','dessen','der','die'],
    explanation:'deren = whose (Femininum\/Plural Genitiv).' },
  { id:'B2_gr_208', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Das Kind, ___ Fahrrad kaputt ist, weint.',
    answer:'dessen', options:['dessen','deren','dem','das'],
    explanation:'dessen f\u00fcr Neutrum (das Kind).' },
  { id:'B2_gr_209', level:'B2', topic:'Relative Clauses', type:'fill-blank',
    prompt:'Die Eltern, ___ Sohn ausgezeichnet wurde, sind stolz.',
    answer:'deren', options:['deren','dessen','die','denen'],
    explanation:'deren f\u00fcr Plural (die Eltern).' },
  { id:'B2_gr_210', level:'B2', topic:'Relative Clauses', type:'mcq',
    prompt:'"Dessen" ist der Genitiv von...',
    answer:'der\/das', options:['der\/das','die','die (Plural)','der (Femininum)'],
    explanation:'dessen = Genitiv von der (Mask) und das (Neutr).' },

  // ── Indefinite Pronouns (5) ──
  { id:'B2_gr_211', level:'B2', topic:'Indefinite Pronouns', type:'fill-blank',
    prompt:'___ kann Deutsch lernen, wenn er will.',
    answer:'Jeder', options:['Jeder','Man','Niemand','Etwas'],
    explanation:'jeder = everyone\/each person.' },
  { id:'B2_gr_212', level:'B2', topic:'Indefinite Pronouns', type:'fill-blank',
    prompt:'___ hat die T\u00fcr ge\u00f6ffnet.',
    answer:'Jemand', options:['Jemand','Niemand','Man','Alle'],
    explanation:'jemand = someone.' },
  { id:'B2_gr_213', level:'B2', topic:'Indefinite Pronouns', type:'fill-blank',
    prompt:'___ hat angerufen. (no one)',
    answer:'Niemand', options:['Niemand','Jemand','Man','Jeder'],
    explanation:'niemand = no one.' },
  { id:'B2_gr_214', level:'B2', topic:'Indefinite Pronouns', type:'fill-blank',
    prompt:'___ soll sich an die Regeln halten.',
    answer:'Man', options:['Man','Jeder','Niemand','Jemand'],
    explanation:'man = one\/you (general statement).' },
  { id:'B2_gr_215', level:'B2', topic:'Indefinite Pronouns', type:'fill-blank',
    prompt:'Ich habe ___ Interessantes geh\u00f6rt.',
    answer:'etwas', options:['etwas','jemand','niemand','man'],
    explanation:'etwas = something.' },

  // ── Negation Patterns (5) ──
  { id:'B2_gr_216', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Ich habe ___ Zeit. (kein)',
    answer:'keine', options:['keine','nicht','nicht einmal','noch nicht'],
    explanation:'kein + Nomen (nicht + Nomen ohne Artikel = kein).' },
  { id:'B2_gr_217', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Das war ___ einfach, sondern schwer.',
    answer:'nicht', options:['nicht','kein','nie','nichts'],
    explanation:'nicht (vor Adjektiv).' },
  { id:'B2_gr_218', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Er hat ___ die Pr\u00fcfung bestanden.',
    answer:'nicht einmal', options:['nicht einmal','nie','nichts','kein'],
    explanation:'nicht einmal = not even.' },
  { id:'B2_gr_219', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Ich habe ___ davon geh\u00f6rt.',
    answer:'nichts', options:['nichts','nie','nicht','kein'],
    explanation:'nichts = nothing.' },
  { id:'B2_gr_220', level:'B2', topic:'Negation', type:'mcq',
    prompt:'"Ich habe keine Zeit" vs "Ich habe nicht Zeit" - Was ist richtig?',
    answer:'keine Zeit', options:['keine Zeit','nicht Zeit','beide sind richtig','kein Zeit'],
    explanation:'kein vor Nomen ohne Artikel. "Keine Zeit" ist korrekt.' },

  // ── Subjunctive II W\u00fcn\u00adsche (all remaining) (5) ──
  { id:'B2_gr_221', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'___ ich doch Urlaub! (haben - Wunsch)',
    answer:'H\u00e4tte', options:['H\u00e4tte','Habe','Hatte','W\u00fcrde haben'],
    explanation:'Irrealer Wunsch: H\u00e4tte ich doch...' },
  { id:'B2_gr_222', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn ich nur mehr Geld ___! (haben - KII)',
    answer:'h\u00e4tte', options:['h\u00e4tte','habe','hatte','w\u00fcrde haben'],
    explanation:'Wenn ich nur + KII (irrealer Wunsch).' },
  { id:'B2_gr_223', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'___ sie doch bald anrufen! (KII)',
    answer:'W\u00fcrde', options:['W\u00fcrde','Wird','Will','Wollte'],
    explanation:'W\u00fcrde + Infinitiv f\u00fcr irrealen Wunsch.' },
  { id:'B2_gr_224', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Wenn es doch ___ regnen w\u00fcrde! (aufh\u00f6ren)',
    answer:'aufh\u00f6ren', options:['aufh\u00f6ren','aufh\u00f6rt','aufgeh\u00f6rt','h\u00f6rt auf'],
    explanation:'w\u00fcrde + Infinitiv (irrealer Wunsch).' },
  { id:'B2_gr_225', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'W\u00e4re ich doch nie dort ___! (hingehen)',
    answer:'hingegangen', options:['hingegangen','hingehen','gegangen','hingeht'],
    explanation:'KII Vergangenheit: w\u00e4re + Partizip II (Bereuung).' },

  // ── More Passive / Miscellaneous B2 (25 more to reach 250) ──
  { id:'B2_gr_226', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Der Vertrag ___ morgen unterschrieben. (werden - Pr\u00e4sens)',
    answer:'wird', options:['wird','wurde','ist','hat'],
    explanation:'Vorgangspassiv Pr\u00e4sens: werden + Partizip II.' },
  { id:'B2_gr_227', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'In diesem Haus ___ schon lange nicht mehr ___. (wohnen - Passiv)',
    answer:'wird gewohnt', options:['wird gewohnt','ist gewohnt','hat gewohnt','wohnt man'],
    explanation:'Unpers\u00f6nliches Passiv: es wird + Partizip II.' },
  { id:'B2_gr_228', level:'B2', topic:'Advanced Passive', type:'fill-blank',
    prompt:'Gestern ___ viel ___ (tanzen - Passiv unpers\u00f6nlich).',
    answer:'wurde getanzt', options:['wurde getanzt','wird getanzt','ist getanzt','hat getanzt'],
    explanation:'Unpers\u00f6nliches Passiv Pr\u00e4teritum.' },
  { id:'B2_gr_229', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Er ___ nicht so laut! (sein - Verbot im KII)',
    answer:'w\u00e4re', options:['w\u00e4re','ist','war','sei'],
    explanation:'KII als mildere Aufforderung.' },
  { id:'B2_gr_230', level:'B2', topic:'Subjunctive II', type:'fill-blank',
    prompt:'Man ___ fr\u00fcher kommen! (sollen - KII Empfehlung)',
    answer:'sollte', options:['sollte','soll','sollte haben','soll sein'],
    explanation:'Man sollte = man sollte (Empfehlung im KII).' },
  { id:'B2_gr_231', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Die Frist ist kurz, ___ m\u00fcssen wir schnell handeln.',
    answer:'deshalb', options:['deshalb','trotzdem','obwohl','weil'],
    explanation:'deshalb = therefore (konsekutiv).' },
  { id:'B2_gr_232', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Er war flei\u00dfig, ___ hat er die Pr\u00fcfung bestanden.',
    answer:'deshalb', options:['deshalb','trotzdem','obwohl','weil'],
    explanation:'deshalb verbindet Grund und Folge.' },
  { id:'B2_gr_233', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Sie spart Geld, ___ sie ein Haus kaufen kann.',
    answer:'damit', options:['damit','weil','obwohl','deshalb'],
    explanation:'damit = so that (final).' },
  { id:'B2_gr_234', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ die Sonne aufging, begannen die V\u00f6gel zu singen.',
    answer:'Sobald', options:['Sobald','Bis','Nachdem','W\u00e4hrend'],
    explanation:'sobald = as soon as (unmittelbar danach).' },
  { id:'B2_gr_235', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ zehn Jahren lebt sie in M\u00fcnchen.',
    answer:'Seit', options:['Seit','Bis','Vor','Nach'],
    explanation:'seit + Dativ = since (Zeitdauer bis jetzt).' },
  { id:'B2_gr_236', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Er ist nicht gekommen, ___ er hatte keine Zeit.',
    answer:'denn', options:['denn','weil','da','obwohl'],
    explanation:'denn (Hauptsatz, Position 0) = because.' },
  { id:'B2_gr_237', level:'B2', topic:'Connectors', type:'mcq',
    prompt:'"Trotzdem" leitet einen ___ ein.',
    answer:'Hauptsatz', options:['Hauptsatz','Nebensatz','Infinitivsatz','Relativsatz'],
    explanation:'trotzdem = nevertheless (Hauptsatz, Verb Position 2).' },
  { id:'B2_gr_238', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Die Kinder spielen ___ dem Garten.',
    answer:'in', options:['in','an','auf','neben'],
    explanation:'in + Dativ (Position wo?).' },
  { id:'B2_gr_239', level:'B2', topic:'Two-way Prepositions', type:'fill-blank',
    prompt:'Die Kinder laufen ___ den Garten.',
    answer:'in', options:['in','an','auf','neben'],
    explanation:'in + Akkusativ (Richtung wohin?).' },
  { id:'B2_gr_240', level:'B2', topic:'Temporal Subclauses', type:'fill-blank',
    prompt:'___ er studiert hat, hat er in einer Firma gearbeitet.',
    answer:'W\u00e4hrend', options:['W\u00e4hrend','Nachdem','Bevor','Seitdem'],
    explanation:'w\u00e4hrend = while (gleichzeitige Handlungen).' },
  { id:'B2_gr_241', level:'B2', topic:'Indirect Questions', type:'sentence-correction',
    prompt:'Correct: "Wann kommt der Bus?" \u2192 (indirekte Frage)',
    answer:'Kannst du mir sagen, wann der Bus kommt?',
    explanation:'Indirekte W-Frage: Fragewort bleibt, Verb ans Ende.' },
  { id:'B2_gr_242', level:'B2', topic:'Relative Clauses', type:'mcq',
    prompt:'"Die Stadt, in der ich geboren bin" - "in der" bezieht sich auf...',
    answer:'die Stadt (weiblich, Dativ)', options:['die Stadt (weiblich, Dativ)','die Stadt (m\u00e4nnlich, Dativ)','die Stadt (weiblich, Akkusativ)','das Dorf (Neutrum, Dativ)'],
    explanation:'die Stadt (Femininum), Relativpronomen: in der (Dativ).' },
  { id:'B2_gr_243', level:'B2', topic:'Connectors', type:'fill-blank',
    prompt:'Er wei\u00df nicht, ___ er kommen kann.',
    answer:'ob', options:['ob','wann','dass','weil'],
    explanation:'ob = whether (indirekte Frage).' },
  { id:'B2_gr_244', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Das ist ___ wahr.',
    answer:'nicht', options:['nicht','kein','nie','nichts'],
    explanation:'nicht vor Adjektiven: nicht wahr.' },
  { id:'B2_gr_245', level:'B2', topic:'Negation', type:'fill-blank',
    prompt:'Ich habe noch ___ so etwas gesehen. (nie)',
    answer:'nie', options:['nie','nicht','kein','nichts'],
    explanation:'noch nie = never before.' },
  { id:'B2_gr_246', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Er tr\u00e4gt ein ___ Hemd. (wei\u00df)',
    answer:'wei\u00dfes', options:['wei\u00dfes','wei\u00dfen','wei\u00dfe','wei\u00dfer'],
    explanation:'Neutrum Akkusativ (nach ein): ein wei\u00dfes Hemd.' },
  { id:'B2_gr_247', level:'B2', topic:'Adjective Declension', type:'fill-blank',
    prompt:'Das ist der ___ Film des Jahres. (gut)',
    answer:'beste', options:['beste','besten','bester','bestes'],
    explanation:'Bestimmter Artikel + Superlativ: der beste Film.' },
  { id:'B2_gr_248', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Wor\u00fcber sprecht ihr? \u2192 Wir sprechen ___. (dar\u00fcber)',
    answer:'dar\u00fcber', options:['dar\u00fcber','darauf','davon','daran'],
    explanation:'\u00fcber + Akk = dar\u00fcber (r wegen Vokal).' },
  { id:'B2_gr_249', level:'B2', topic:'Prepositional Adverbs', type:'fill-blank',
    prompt:'Wovon tr\u00e4umst du? \u2192 Ich tr\u00e4ume ___.',
    answer:'davon', options:['davon','daran','darauf','dadurch'],
    explanation:'von tr\u00e4umen \u2192 wovon - davon.' },
  { id:'B2_gr_250', level:'B2', topic:'Complex Passive', type:'fill-blank',
    prompt:'Der Patient ___ untersucht ___ (m\u00fcssen - Satz: muss + werden).',
    answer:'muss werden', options:['muss werden','wird m\u00fcssen','hat werden m\u00fcssen','musste werden'],
    explanation:'Modalverb Passiv Pr\u00e4sens: muss + Partizip II + werden.' },
];

// Combine
data.B2 = [...existing, ...newExercises];

// Validate
const ids = data.B2.map(e => e.id);
const dupIds = ids.filter((id, i) => ids.indexOf(id) !== i);
if (dupIds.length > 0) {
  console.error('DUPLICATE IDs:', [...new Set(dupIds)].join(', '));
  process.exit(1);
}

console.log('Total B2 grammar:', data.B2.length);
console.log('New exercises added:', newExercises.length);
console.log('Duplicate IDs: none');

// Check all have required fields
const missing = data.B2.filter(e => !e.id || !e.level || !e.type || !e.prompt || !e.answer);
if (missing.length > 0) {
  console.error('Missing required fields:', missing.map(e => e.id).join(', '));
  process.exit(1);
}
console.log('All required fields present');

// Check topic field
const noTopic = data.B2.filter(e => !e.topic);
if (noTopic.length > 0) {
  console.log('Entries without topic:', noTopic.map(e => e.id).join(', '));
}

// Write
writeFileSync(path, JSON.stringify(data, null, 2) + '\n', 'utf8');
console.log('File written.');
