import fs from 'fs';

const reading = JSON.parse(fs.readFileSync('src/data/reading.json', 'utf8'));

const existing = reading.B2.slice(0, 3);
existing[0].lessonId = 'B2_lesson_16';
existing[1].lessonId = 'B2_lesson_7';
existing[2].lessonId = 'B2_lesson_2';

const lessonSeq = [];
for (let i = 1; i <= 25; i++) lessonSeq.push(`B2_lesson_${i}`);
for (let i = 1; i <= 22; i++) lessonSeq.push(`B2_lesson_${i}`);

const newPassages = [
  {id:'B2_read_4', lessonId:'B2_lesson_1', title:'Der Pharmamarkt in Deutschland', text:'Die Pharmaindustrie ist einer der wichtigsten Wirtschaftszweige in Deutschland. Jaehrlich werden Milliarden in die Entwicklung neuer Medikamente investiert. Grosse Unternehmen wie Bayer und Merck haben ihren Sitz in Deutschland. Kritiker bemaengeln die hohen Preise vieler Medikamente. Sie fordern mehr staatliche Kontrolle. Die Industrie argumentiert, dass die hohen Kosten fuer Forschung und Entwicklung die Preise rechtfertigen.',
   questions:[{id:'b2r4a',type:'mcq',question:'Warum sind Medikamente nach Meinung der Industrie teuer?',options:['Hohe Steuern','Forschung und Entwicklung kosten viel','Die Aerzte verdienen zu viel','Die Apotheken verlangen zu viel'],answer:'Forschung und Entwicklung kosten viel'},{id:'b2r4b',type:'true-false',question:'Bayer und Merck sind deutsche Unternehmen.',answer:'true'},{id:'b2r4c',type:'mcq',question:'Was fordern Kritiker?',options:['Mehr Werbung','Mehr staatliche Kontrolle','Weniger Medikamente','Hoehere Preise'],answer:'Mehr staatliche Kontrolle'}]},
  {id:'B2_read_5', lessonId:'B2_lesson_2', title:'Studie: Bewegung verbessert Gedaechtnis', text:'Eine neue Studie der Universitaet Heidelberg zeigt, dass regelmaessige Bewegung das Gedaechtnis verbessern kann. Ueber 500 Probanden nahmen an der Untersuchung teil. Die Haelfte machte dreimal pro Woche Ausdauersport, die andere Haelfte blieb inaktiv. Nach sechs Monaten zeigte die Sportgruppe deutlich bessere Ergebnisse bei Gedaechtnistests. Die Forscher empfehlen daher, mindestens 150 Minuten moderate Bewegung pro Woche einzuplanen.',
   questions:[{id:'b2r5a',type:'mcq',question:'Wie viele Probanden nahmen an der Studie teil?',options:['100','300','500','1000'],answer:'500'},{id:'b2r5b',type:'true-false',question:'Die Sportgruppe zeigte nach sechs Monaten bessere Gedaechtnisleistungen.',answer:'true'},{id:'b2r5c',type:'mcq',question:'Wie viel Bewegung pro Woche empfehlen die Forscher?',options:['30 Minuten','90 Minuten','150 Minuten','300 Minuten'],answer:'150 Minuten'}]},
  {id:'B2_read_6', lessonId:'B2_lesson_3', title:'Die Reform der Pflegeversicherung', text:'Die Bundesregierung plant eine umfassende Reform der Pflegeversicherung. Die Zahl der Pflegebeduerftigen steigt stetig, waehrend die Beitraege zur Pflegeversicherung kaum noch ausreichen. Experten schlagen vor, die Beitraege zu erhoehen und gleichzeitig die Leistungen zu verbessern. Pflegekraefte fordern bessere Arbeitsbedingungen und hoehere Loehne. Die Reform soll bis zum naechsten Jahr verabschiedet werden.',
   questions:[{id:'b2r6a',type:'mcq',question:'Warum ist eine Reform der Pflegeversicherung noetig?',options:['Weil es zu wenig Krankenhaeuser gibt','Weil die Zahl der Pflegebeduerftigen steigt','Weil die Aerzte streiken','Weil die Krankenkassen pleite sind'],answer:'Weil die Zahl der Pflegebeduerftigen steigt'},{id:'b2r6b',type:'true-false',question:'Pflegekraefte fordern bessere Arbeitsbedingungen.',answer:'true'},{id:'b2r6c',type:'mcq',question:'Was schlagen Experten vor?',options:['Beitraege senken','Beitraege erhoehen und Leistungen verbessern','Die Pflegeversicherung abschaffen','Private Pflege verbieten'],answer:'Beitraege erhoehen und Leistungen verbessern'}]},
  {id:'B2_read_7', lessonId:'B2_lesson_4', title:'Literatur im Wartezimmer', text:'Immer mehr Arztpraxen in Deutschland bieten ihren Patienten nicht nur medizinische Versorgung, sondern auch Zugang zu Literatur. In speziellen Buecherregalen im Wartezimmer koennen Patienten kostenlos Buecher ausleihen oder tauschen. Die Aktion heisst "Lesen gegen Wartezeit" und wird vom Deutschen Literaturfonds unterstuetzt. Viele Patienten schaetzen das Angebot und nehmen regelmaessig neue Buecher mit.',
   questions:[{id:'b2r7a',type:'mcq',question:'Was bieten manche Arztpraxen zusaetzlich an?',options:['Kostenloses WLAN','Buecher zum Ausleihen oder Tauschen','Kostenlose Getraenke','Yoga-Stunden'],answer:'Buecher zum Ausleihen oder Tauschen'},{id:'b2r7b',type:'true-false',question:'Die Aktion heisst "Buecher fuer alle".',answer:'false'},{id:'b2r7c',type:'opinion-match',question:'Wie reagieren die Patienten auf das Angebot?',options:['Sie ignorieren es','Sie schaetzen es','Sie beschweren sich','Sie bezahlen dafuer'],answer:'Sie schaetzen es'}]},
  {id:'B2_read_8', lessonId:'B2_lesson_5', title:'Aerzte aus dem Ausland', text:'Deutschland ist auf Aerzte aus dem Ausland angewiesen. Fast jeder vierte Arzt in deutschen Krankenhaeusern hat einen Migrationshintergrund. Viele kommen aus Syrien, der Tuerkei oder osteuropaeischen Laendern. Die Integration dieser Fachkraefte ist nicht immer einfach. Sprachbarrieren und unterschiedliche Ausbildungssysteme stellen Herausforderungen dar. Trotzdem sind auslaendische Aerzte eine wichtige Stuetze des Gesundheitssystems.',
   questions:[{id:'b2r8a',type:'mcq',question:'Wie viele Aerzte in Deutschland haben einen Migrationshintergrund?',options:['Jeder zehnte','Jeder vierte','Jeder zweite','Fast alle'],answer:'Jeder vierte'},{id:'b2r8b',type:'mcq',question:'Was sind Herausforderungen fuer die Integration auslaendischer Aerzte?',options:['Zu hohe Gehaelter','Sprachbarrieren und unterschiedliche Ausbildungssysteme','Zu viele Urlaubstage','Zu kurze Arbeitszeiten'],answer:'Sprachbarrieren und unterschiedliche Ausbildungssysteme'},{id:'b2r8c',type:'true-false',question:'Auslaendische Aerzte sind eine wichtige Stuetze des Gesundheitssystems.',answer:'true'}]},
  {id:'B2_read_9', lessonId:'B2_lesson_6', title:'Globale Gesundheitsrisiken', text:'Die Globalisierung hat auch Auswirkungen auf die Gesundheit. Krankheiten verbreiten sich schneller als frueher. Der internationale Reiseverkehr traegt dazu bei, dass Viren innerhalb weniger Stunden um die Welt transportiert werden koennen. Die Weltgesundheitsorganisation (WHO) arbeitet daran, Fruehwarnsysteme zu verbessern. Experten fordern mehr internationale Zusammenarbeit in der Gesundheitsforschung.',
   questions:[{id:'b2r9a',type:'mcq',question:'Warum verbreiten sich Krankheiten heute schneller?',options:['Weil es mehr Menschen gibt','Wegen des internationalen Reiseverkehrs','Weil die Medizin schlechter ist','Wegen des Klimawandels'],answer:'Wegen des internationalen Reiseverkehrs'},{id:'b2r9b',type:'true-false',question:'Die WHO arbeitet an besseren Fruehwarnsystemen.',answer:'true'},{id:'b2r9c',type:'mcq',question:'Was fordern Experten?',options:['Mehr Reisewarnungen','Mehr internationale Zusammenarbeit in der Gesundheitsforschung','Weniger Flugreisen','Hoehere Steuern'],answer:'Mehr internationale Zusammenarbeit in der Gesundheitsforschung'}]},
  {id:'B2_read_10', lessonId:'B2_lesson_7', title:'Ethische Fragen in der Notaufnahme', text:'In der Notaufnahme muessen Aerzte oft schwierige Entscheidungen treffen. Wenn nicht genug Betten oder Beatmungsgeraete vorhanden sind, muessen sie entscheiden, welcher Patient zuerst behandelt wird. Diese Triage genannte Entscheidung folgt medizinischen Kriterien. Ethische Grundsaetze wie Gerechtigkeit und Fuersorge spielen dabei eine grosse Rolle. Einige Kliniken haben Ethikkomitees, die das Personal bei solchen Entscheidungen beraten.',
   questions:[{id:'b2r10a',type:'mcq',question:'Was bedeutet Triage in der Notaufnahme?',options:['Eine Operation','Die Entscheidung, wer zuerst behandelt wird','Die Entlassung eines Patienten','Die Verlegung in ein anderes Krankenhaus'],answer:'Die Entscheidung, wer zuerst behandelt wird'},{id:'b2r10b',type:'true-false',question:'Ethikkomitees beraten das Personal bei schwierigen Entscheidungen.',answer:'true'},{id:'b2r10c',type:'mcq',question:'Welche ethischen Grundsaetze sind bei der Triage wichtig?',options:['Gewinn und Verlust','Gerechtigkeit und Fuersorge','Schnelligkeit und Effizienz','Kosten und Nutzen'],answer:'Gerechtigkeit und Fuersorge'}]},
  {id:'B2_read_11', lessonId:'B2_lesson_8', title:'Die schriftliche Bewerbung als Arzt', text:'Eine Bewerbung als Arzt unterscheidet sich in einigen Punkten von anderen Bewerbungen. Neben dem ueblichen Anschreiben und Lebenslauf werden oft ein akademisches Zeugnis, eine Approbationsurkunde und Referenzen erwartet. Im Anschreiben sollte der Bewerber seine klinische Erfahrung und Spezialisierung erwaehnen. Personalverantwortliche achten besonders auf die Motivation und die berufliche Entwicklung des Kandidaten.',
   questions:[{id:'b2r11a',type:'mcq',question:'Welche Dokumente werden bei einer Arztbewerbung oft zusaetzlich erwartet?',options:['Fuehrerschein und Reisepass','Approbationsurkunde und akademisches Zeugnis','Sprachzertifikat und Visum','Arbeitsvertrag und Gehaltsabrechnung'],answer:'Approbationsurkunde und akademisches Zeugnis'},{id:'b2r11b',type:'true-false',question:'Im Anschreiben sollte man seine klinische Erfahrung erwaehnen.',answer:'true'},{id:'b2r11c',type:'mcq',question:'Worauf achten Personalverantwortliche besonders?',options:['Das Alter des Bewerbers','Die Motivation und berufliche Entwicklung','Den Wohnort','Die Hobbys'],answer:'Die Motivation und berufliche Entwicklung'}]},
  {id:'B2_read_12', lessonId:'B2_lesson_9', title:'Nachhaltigkeit im Krankenhaus', text:'Krankenhaeuser verbrauchen grosse Mengen an Energie und produzieren viel Muell. Ein durchschnittliches Krankenhaus erzeugt pro Bett etwa drei Kilogramm Abfall pro Tag. Viele Kliniken versuchen jetzt, nachhaltiger zu arbeiten. Sie trennen Muell besser, nutzen wiederverwendbare Materialien und sparen Energie. Einige Krankenhaeuser haben sogar eigene Solaranlagen auf dem Dach installiert.',
   questions:[{id:'b2r12a',type:'mcq',question:'Wie viel Abfall produziert ein durchschnittliches Krankenhaus pro Bett und Tag?',options:['1 kg','3 kg','5 kg','10 kg'],answer:'3 kg'},{id:'b2r12b',type:'true-false',question:'Einige Krankenhaeuser haben Solaranlagen auf dem Dach.',answer:'true'},{id:'b2r12c',type:'mcq',question:'Welche Massnahmen ergreifen Kliniken fuer mehr Nachhaltigkeit?',options:['Mehr Muell produzieren','Energie sparen und Muell besser trennen','Weniger Patienten behandeln','Hoehere Preise verlangen'],answer:'Energie sparen und Muell besser trennen'}]},
  {id:'B2_read_13', lessonId:'B2_lesson_10', title:'Private oder gesetzliche Krankenversicherung?', text:'In Deutschland koennen die meisten Arbeitnehmer zwischen der gesetzlichen und der privaten Krankenversicherung waehlen. Die gesetzliche Versicherung richtet sich nach dem Einkommen. Die Beitraege sind fuer alle Mitglieder gleich. Die private Versicherung bietet oft bessere Leistungen, ist aber fuer aeltere Menschen teurer. Fuer Selbststaendige und Gutverdiener kann die private Versicherung guenstiger sein. Die Wahl sollte gut ueberlegt sein.',
   questions:[{id:'b2r13a',type:'mcq',question:'Wie berechnet sich der Beitrag in der gesetzlichen Versicherung?',options:['Nach dem Alter','Nach dem Einkommen','Nach der Krankheit','Nach der Familiengroesse'],answer:'Nach dem Einkommen'},{id:'b2r13b',type:'true-false',question:'Die private Krankenversicherung ist fuer aeltere Menschen guenstiger.',answer:'false'},{id:'b2r13c',type:'mcq',question:'Fuer wen kann die private Versicherung guenstiger sein?',options:['Fuer Rentner','Fuer Selbststaendige und Gutverdiener','Fuer Arbeitslose','Fuer Studenten'],answer:'Fuer Selbststaendige und Gutverdiener'}]},
  {id:'B2_read_14', lessonId:'B2_lesson_11', title:'Gesundheitsversorgung fuer Gefluechtete', text:'Die medizinische Versorgung von Gefluechteten ist in Deutschland gesetzlich geregelt. In den ersten 18 Monaten erhalten sie nur Leistungen bei akuten Erkrankungen und Schmerzen. Danach haben sie Anspruch auf die gleiche Versorgung wie gesetzlich Versicherte. Viele Staedte haben spezielle Gesundheitszentren fuer Gefluechtete eingerichtet. Sprachmittler helfen bei der Kommunikation zwischen Aerzten und Patienten.',
   questions:[{id:'b2r14a',type:'mcq',question:'Welche medizinischen Leistungen erhalten Gefluechtete in den ersten 18 Monaten?',options:['Alle Leistungen','Nur Leistungen bei akuten Erkrankungen und Schmerzen','Nur Zahnbehandlung','Keine Leistungen'],answer:'Nur Leistungen bei akuten Erkrankungen und Schmerzen'},{id:'b2r14b',type:'true-false',question:'Sprachmittler helfen bei der Kommunikation zwischen Aerzten und Patienten.',answer:'true'},{id:'b2r14c',type:'mcq',question:'Was haben Staedte fuer Gefluechtete eingerichtet?',options:['Eigene Krankenhaeuser','Spezielle Gesundheitszentren','Mobile Arztpraxen','Apotheken'],answer:'Spezielle Gesundheitszentren'}]},
  {id:'B2_read_15', lessonId:'B2_lesson_12', title:'Die Patientenverfuegung', text:'Eine Patientenverfuegung ist ein wichtiges Dokument. Darin legt eine Person schriftlich fest, welche medizinischen Massnahmen sie in bestimmten Situationen wuenscht oder ablehnt. Zum Beispiel kann man bestimmen, ob man im Fall einer schweren Erkrankung kuenstlich beatmet werden moechte. Die Verfuegung sollte regelmaessig aktualisiert werden. Sie ist nur gueltig, wenn die Person zum Zeitpunkt des Verfassens geschaeftsfaehig war.',
   questions:[{id:'b2r15a',type:'mcq',question:'Was legt eine Patientenverfuegung fest?',options:['Die Wahl des Krankenhauses','Die gewuenschten medizinischen Massnahmen','Die Kostenuebernahme','Den Hausarzt'],answer:'Die gewuenschten medizinischen Massnahmen'},{id:'b2r15b',type:'true-false',question:'Eine Patientenverfuegung sollte regelmaessig aktualisiert werden.',answer:'true'},{id:'b2r15c',type:'mcq',question:'Wann ist eine Patientenverfuegung gueltig?',options:['Wenn ein Arzt sie unterschreibt','Wenn die Person geschaeftsfaehig war','Wenn die Familie zustimmt','Wenn ein Notar sie beglaubigt'],answer:'Wenn die Person geschaeftsfaehig war'}]},
  {id:'B2_read_16', lessonId:'B2_lesson_13', title:'Gesundheitsinformationen im Internet', text:'Immer mehr Menschen suchen im Internet nach Gesundheitsinformationen. Das Problem ist, dass nicht alle Quellen vertrauenswuerdig sind. Experten empfehlen, nur Seiten von offiziellen Institutionen wie dem Robert Koch-Institut oder der Bundesaerztekammer zu nutzen. Auch Patientenforen koennen hilfreich sein, aber die Informationen dort ersetzen keinen Arztbesuch. Eine Studie zeigt, dass ueber 70 Prozent der Deutschen online nach Symptomen suchen, bevor sie einen Arzt aufsuchen.',
   questions:[{id:'b2r16a',type:'mcq',question:'Welche Quellen empfehlen Experten fuer Gesundheitsinformationen?',options:['Social Media','Seiten offizieller Institutionen','Private Blogs','Wikipedia'],answer:'Seiten offizieller Institutionen'},{id:'b2r16b',type:'true-false',question:'Ueber 70 Prozent der Deutschen suchen online nach Symptomen.',answer:'true'},{id:'b2r16c',type:'mcq',question:'Was gilt fuer Informationen aus Patientenforen?',options:['Sie sind immer richtig','Sie ersetzen keinen Arztbesuch','Sie sind besser als aerztliche Beratung','Sie sind kostenpflichtig'],answer:'Sie ersetzen keinen Arztbesuch'}]},
  {id:'B2_read_17', lessonId:'B2_lesson_14', title:'Burnout bei medizinischem Personal', text:'Das Burnout-Risiko bei Aerzten und Pflegekraeften ist hoch. Lange Arbeitszeiten, emotionaler Stress und buerokratische Aufgaben belasten das Personal. Studien zeigen, dass etwa jeder dritte Arzt Symptome von Burnout zeigt. Krankenhaeuser bieten zunehmend Praeventionsprogramme an, wie zum Beispiel Workshops zur Stressbewaeltigung oder Supervision fuer Mitarbeiter. Experten betonen, dass eine gesunde Work-Life-Balance wichtig ist, um langfristig gesund zu bleiben.',
   questions:[{id:'b2r17a',type:'mcq',question:'Wie viele Aerzte zeigen Symptome von Burnout?',options:['Jeder zehnte','Jeder dritte','Jeder zweite','Fast alle'],answer:'Jeder dritte'},{id:'b2r17b',type:'true-false',question:'Krankenhaeuser bieten zunehmend Praeventionsprogramme an.',answer:'true'},{id:'b2r17c',type:'mcq',question:'Welche Massnahmen helfen laut Experten gegen Burnout?',options:['Mehr Ueberstunden','Eine gesunde Work-Life-Balance','Weniger Urlaub','Mehr Buerokratie'],answer:'Eine gesunde Work-Life-Balance'}]},
  {id:'B2_read_18', lessonId:'B2_lesson_15', title:'Medizintourismus in Deutschland', text:'Deutschland ist ein beliebtes Ziel fuer Medizintouristen. Jaehrlich reisen Tausende aus dem Ausland an, um sich in deutschen Krankenhaeusern behandeln zu lassen. Besonders gefragt sind Orthopaedie, Krebsbehandlungen und Herzoperationen. Die Patienten kommen vor allem aus arabischen Laendern, Russland und den USA. Deutsche Kliniken haben spezielle Abteilungen fuer internationale Patienten und bieten Dolmetscherdienste an.',
   questions:[{id:'b2r18a',type:'mcq',question:'Welche Behandlungen sind bei Medizintouristen besonders gefragt?',options:['Zahnbehandlung','Orthopaedie, Krebsbehandlungen und Herzoperationen','Hautpflege','Psychotherapie'],answer:'Orthopaedie, Krebsbehandlungen und Herzoperationen'},{id:'b2r18b',type:'true-false',question:'Deutsche Kliniken haben spezielle Abteilungen fuer internationale Patienten.',answer:'true'},{id:'b2r18c',type:'mcq',question:'Warum suchen Patienten Deutschland fuer Behandlungen auf?',options:['Weil es guenstiger ist','Wegen der medizinischen Qualitaet','Weil es waermer ist','Weil es keine Wartezeiten gibt'],answer:'Wegen der medizinischen Qualitaet'}]},
  {id:'B2_read_19', lessonId:'B2_lesson_16', title:'Die elektronische Patientenakte', text:'Seit 2021 wird in Deutschland die elektronische Patientenakte (ePA) eingefuehrt. Sie soll medizinische Daten wie Befunde, Medikationsplaene und Impfungen digital speichern. Patienten koennen selbst entscheiden, welche Daten sie freigeben. Aerzte haben dann mit Einwilligung des Patienten Zugriff auf die Daten. Die ePA soll die Behandlung verbessern und Doppeluntersuchungen vermeiden. Allerdings gibt es Bedenken bezueglich des Datenschutzes.',
   questions:[{id:'b2r19a',type:'mcq',question:'Welche Daten koennen in der ePA gespeichert werden?',options:['Nur Impfungen','Befunde, Medikationsplaene und Impfungen','Nur Roentgenbilder','Nur die Krankenakte des Hausarztes'],answer:'Befunde, Medikationsplaene und Impfungen'},{id:'b2r19b',type:'true-false',question:'Patienten entscheiden selbst, welche Daten sie freigeben.',answer:'true'},{id:'b2r19c',type:'mcq',question:'Welche Bedenken gibt es zur ePA?',options:['Sie ist zu teuer','Bedenken bezueglich des Datenschutzes','Sie funktioniert nicht','Nur wenige Aerzte nutzen sie'],answer:'Bedenken bezueglich des Datenschutzes'}]},
  {id:'B2_read_20', lessonId:'B2_lesson_17', title:'Das deutsche Impfprogramm', text:'Die Staendige Impfkommission (STIKO) gibt in Deutschland Empfehlungen fuer Impfungen heraus. Sie besteht aus unabhaengigen Experten. Die STIKO bewertet, welche Impfungen fuer welche Altersgruppen sinnvoll sind. Die Empfehlungen sind nicht verpflichtend, werden aber von den Krankenkassen uebernommen. In den letzten Jahren gab es immer wieder Diskussionen ueber die Impfpflicht, zum Beispiel bei der Masernimpfung fuer Kinder in Kitas und Schulen.',
   questions:[{id:'b2r20a',type:'mcq',question:'Wer gibt Impfempfehlungen in Deutschland?',options:['Die Bundesregierung','Die STIKO','Die Krankenkassen','Der Bundespraesident'],answer:'Die STIKO'},{id:'b2r20b',type:'true-false',question:'Die Impfempfehlungen der STIKO sind verpflichtend.',answer:'false'},{id:'b2r20c',type:'mcq',question:'Fuer welche Impfung gab es Diskussionen ueber eine Impfpflicht?',options:['Grippe','Masern','Tetanus','COVID-19'],answer:'Masern'}]},
  {id:'B2_read_21', lessonId:'B2_lesson_18', title:'Gruene Oasen in der Stadt', text:'Staedte werden immer dichter bebaut. Parks und Gruenflaechen sind wichtiger denn je. Sie verbessern nicht nur das Stadtklima, sondern auch die Gesundheit der Bewohner. Studien zeigen, dass Menschen, die in der Naehe von Parks wohnen, seltener an Herz-Kreislauf-Erkrankungen leiden. Einige Staedte foerdern deshalb den Bau von Dachgaerten und begruenten Innenhoefen. Auch Urban Gardening Projekte werden immer beliebter.',
   questions:[{id:'b2r21a',type:'mcq',question:'Welchen gesundheitlichen Vorteil haben Menschen in der Naehe von Parks?',options:['Sie schlafen besser','Sie leiden seltener an Herz-Kreislauf-Erkrankungen','Sie haben weniger Stress','Sie essen gesuender'],answer:'Sie leiden seltener an Herz-Kreislauf-Erkrankungen'},{id:'b2r21b',type:'true-false',question:'Dachgaerten und begruente Innenhoefe werden von Staedten gefoerdert.',answer:'true'},{id:'b2r21c',type:'mcq',question:'Was wird in Staedten immer beliebter?',options:['Hochhaeuser','Urban Gardening Projekte','Parkhaeuser','Einkaufszentren'],answer:'Urban Gardening Projekte'}]},
  {id:'B2_read_22', lessonId:'B2_lesson_19', title:'Klimawandel und Gesundheit', text:'Der Klimawandel hat direkte Auswirkungen auf die Gesundheit. Hitzewellen fuehren zu mehr Kreislaufproblemen und Todesfaellen. Auch Allergien nehmen zu, weil die Pollensaison laenger wird. Tropische Krankheiten wie das West-Nil-Virus breiten sich in Deutschland aus. Das Gesundheitsministerium arbeitet an einem Hitzeschutzplan fuer Krankenhaeuser und Pflegeheime. Aerzte werden zunehmend in Klimafragen geschult.',
   questions:[{id:'b2r22a',type:'mcq',question:'Welche Auswirkung haben Hitzewellen auf die Gesundheit?',options:['Mehr Kopfschmerzen','Mehr Kreislaufprobleme und Todesfaelle','Mehr Erkaeltungen','Weniger Krankheiten'],answer:'Mehr Kreislaufprobleme und Todesfaelle'},{id:'b2r22b',type:'true-false',question:'Tropische Krankheiten breiten sich in Deutschland aus.',answer:'true'},{id:'b2r22c',type:'mcq',question:'Wer arbeitet an einem Hitzeschutzplan?',options:['Die Feuerwehr','Das Gesundheitsministerium','Die Krankenkassen','Der Wetterdienst'],answer:'Das Gesundheitsministerium'}]},
  {id:'B2_read_23', lessonId:'B2_lesson_20', title:'Kleidung im Krankenhaus', text:'Die Kleidung im Krankenhaus hat sich in den letzten Jahren veraendert. Frueher trugen Aerzte weisse Kittel, heute ist bunte Berufskleidung ueblich. Die Kleidung muss hygienischen Standards entsprechen und leicht zu reinigen sein. Viele Krankenhaeuser haben inzwischen einheitliche Kleidungsregeln eingefuehrt. Chirurgen tragen waehrend Operationen sterile Kleidung. Die Farbe der Kleidung kann je nach Abteilung variieren.',
   questions:[{id:'b2r23a',type:'mcq',question:'Welche Farbe trugen Aerzte frueher?',options:['Blau','Weiss','Gruen','Schwarz'],answer:'Weiss'},{id:'b2r23b',type:'true-false',question:'Die Kleidung im Krankenhaus muss hygienischen Standards entsprechen.',answer:'true'},{id:'b2r23c',type:'mcq',question:'Was tragen Chirurgen waehrend Operationen?',options:['Normale Kleidung','Sterile Kleidung','Zivile Kleidung','Uniformen'],answer:'Sterile Kleidung'}]},
  {id:'B2_read_24', lessonId:'B2_lesson_21', title:'Sport nach der Krebsdiagnose', text:'Frueher wurde Krebspatienten empfohlen, sich zu schonen. Heute weiss man, dass Bewegung den Heilungsprozess unterstuetzen kann. Spezielle Sportprogramme fuer Krebspatienten helfen, die Nebenwirkungen der Therapie zu reduzieren. Viele Krankenkassen bezuschussen solche Programme. Die Trainings werden von speziell ausgebildeten Sporttherapeuten geleitet. Die Patienten berichten von mehr Energie und besserer Lebensqualitaet.',
   questions:[{id:'b2r24a',type:'mcq',question:'Was wusste man frueher ueber Bewegung bei Krebs?',options:['Sie war empfohlen','Man empfahl Schonung','Sie spielte keine Rolle','Sie war verboten'],answer:'Man empfahl Schonung'},{id:'b2r24b',type:'true-false',question:'Die Trainings werden von Sporttherapeuten geleitet.',answer:'true'},{id:'b2r24c',type:'mcq',question:'Welche Wirkung berichten Patienten von den Sportprogrammen?',options:['Mehr Muedigkeit','Mehr Energie und bessere Lebensqualitaet','Weniger Appetit','Mehr Schmerzen'],answer:'Mehr Energie und bessere Lebensqualitaet'}]},
  {id:'B2_read_25', lessonId:'B2_lesson_22', title:'Die Geschichte der Krankenpflege', text:'Die moderne Krankenpflege hat sich im 19. Jahrhundert entwickelt. Florence Nightingale, eine britische Krankenschwester, gilt als Begruenderin der professionellen Pflege. Sie verbesserte waehrend des Krimkrieges die Hygiene in den Lazaretten. Ihre Prinzipien gelten bis heute. In Deutschland begann die Ausbildung von Krankenschwestern Mitte des 19. Jahrhunderts. Lange Zeit war die Pflege ein reiner Frauenberuf. Das hat sich in den letzten Jahrzehnten geaendert.',
   questions:[{id:'b2r25a',type:'mcq',question:'Wer gilt als Begruenderin der professionellen Krankenpflege?',options:['Florence Nightingale','Clara Barton','Marie Curie','Hildegard von Bingen'],answer:'Florence Nightingale'},{id:'b2r25b',type:'true-false',question:'Die Ausbildung von Krankenschwestern begann in Deutschland im 20. Jahrhundert.',answer:'false'},{id:'b2r25c',type:'mcq',question:'Was verbesserte Florence Nightingale waehrend des Krimkrieges?',options:['Die Verpflegung','Die Hygiene','Die Medikamente','Die Unterkuenfte'],answer:'Die Hygiene'}]},
  {id:'B2_read_26', lessonId:'B2_lesson_23', title:'Was ist ein guter Arzt?', text:'Die Frage nach dem guten Arzt beschaeftigt die Medizinethik seit Jahrhunderten. Ein guter Arzt sollte nicht nur medizinisches Wissen haben. Empathie, Kommunikationsfaehigkeit und Verantwortungsbewusstsein sind genauso wichtig. Der Philosoph Hans Jonas betonte die Verantwortung des Arztes gegenueber dem Leben. In der medizinischen Ausbildung wird heute mehr Wert auf die Vermittlung ethischer Grundsaetze gelegt als frueher.',
   questions:[{id:'b2r26a',type:'mcq',question:'Welche Eigenschaften sollte ein guter Arzt haben?',options:['Nur medizinisches Wissen','Medizinisches Wissen, Empathie und Verantwortungsbewusstsein','Nur Freundlichkeit','Nur Erfahrung'],answer:'Medizinisches Wissen, Empathie und Verantwortungsbewusstsein'},{id:'b2r26b',type:'true-false',question:'In der medizinischen Ausbildung wird heute mehr Wert auf ethische Grundsaetze gelegt.',answer:'true'},{id:'b2r26c',type:'mcq',question:'Welcher Philosoph betonte die Verantwortung des Arztes?',options:['Immanuel Kant','Hans Jonas','Friedrich Nietzsche','Platon'],answer:'Hans Jonas'}]},
  {id:'B2_read_27', lessonId:'B2_lesson_24', title:'Die Europaeische Krankenversicherungskarte', text:'Mit der Europaeischen Krankenversicherungskarte (EHIC) koennen Reisende aus der EU in allen Mitgliedslaendern medizinische Leistungen erhalten. Die Karte ist kostenlos und wird von den gesetzlichen Krankenkassen ausgestellt. Sie deckt notwendige Behandlungen ab. Fuer private Zusatzleistungen oder geplante Behandlungen im Ausland gilt die Karte nicht. Experten empfehlen, zusaetzlich eine private Reisekrankenversicherung abzuschliessen.',
   questions:[{id:'b2r27a',type:'mcq',question:'Welche Leistungen deckt die EHIC ab?',options:['Alle medizinischen Leistungen weltweit','Notwendige Behandlungen in EU-Laendern','Private Zusatzleistungen','Geplante Operationen im Ausland'],answer:'Notwendige Behandlungen in EU-Laendern'},{id:'b2r27b',type:'true-false',question:'Die EHIC ist kostenlos.',answer:'true'},{id:'b2r27c',type:'mcq',question:'Was empfehlen Experten zusaetzlich zur EHIC?',options:['Eine Reiseruecktrittsversicherung','Eine private Reisekrankenversicherung','Eine Haftpflichtversicherung','Eine Lebensversicherung'],answer:'Eine private Reisekrankenversicherung'}]},
  {id:'B2_read_28', lessonId:'B2_lesson_25', title:'Interkulturelle Kommunikation im Krankenhaus', text:'In deutschen Krankenhaeusern treffen Menschen aus vielen Kulturen aufeinander. Sowohl Patienten als auch Mitarbeiter haben unterschiedliche kulturelle Hintergruende. Missverstaendnisse entstehen oft durch verschiedene Vorstellungen von Krankheit, Heilung und dem Verhalten gegenueber Autoritaeten. Interkulturelle Trainings fuer Klinikpersonal helfen, diese Missverstaendnisse zu vermeiden. Viele Krankenhaeuser bieten solche