const fs = require('fs');

// Read existing words for dedup
const existingTxt = fs.readFileSync('scripts/existing_b2.txt', 'utf-8');
const existing = new Set(existingTxt.split('\n').map(w => w.trim().toLowerCase().replace(/^(der|die|das) /,'')).filter(w=>w));
const batchAdded = new Set();
function nw(w) { return w.trim().toLowerCase().replace(/^(der|die|das) /,''); }
function esc(v) { if(v==null||v==='')return'';const s=String(v);return s.indexOf(',')>=0||s.indexOf('"')>=0?'"'+s.replace(/"/g,'""')+'"':s; }

function word(a,p,pl,tr,ex,pos,top,tag) {
  const w=nw(a); if(existing.has(w)||batchAdded.has(w))return null;
  batchAdded.add(w);
  return ['','B2',esc(a),esc(p||''),esc(pl||''),esc(tr),esc(ex),esc(pos),esc(top),esc(tag),'B2_lesson_general'].join(',');
}
const rows = [];
function add(ar){for(const e of ar){const r=word(e[0],e[1],e[2],e[3],e[4],e[5],e[6],e[7]);if(r)rows.push(r);}}

// ====== B2 WORDS: 20 topics x 25 each = 500 total ======

add([ // 1. Professional Communication (25)
['die Besprechung','die','die Besprechungen','meeting','Die Besprechung findet morgen statt.','noun','Professional communication','b2;top1'],
['der Vorschlag','der','die Vorschläge','suggestion','Der Vorschlag wurde angenommen.','noun','Professional communication','b2;top1'],
['die Präsentation','die','die Präsentationen','presentation','Die Präsentation war überzeugend.','noun','Professional communication','b2;top1'],
['die Zusammenarbeit','die','','cooperation','Die Zusammenarbeit funktioniert gut.','noun','Professional communication','b2;top1'],
['die Verhandlung','die','die Verhandlungen','negotiation','Die Verhandlung dauerte Stunden.','noun','Professional communication','b2;top1'],
['die Bescheinigung','die','die Bescheinigungen','certificate','Die Bescheinigung wurde ausgestellt.','noun','Professional communication','b2;top1'],
['der Vermerk','der','die Vermerke','memo','Der Vermerk wurde verteilt.','noun','Professional communication','b2;top1'],
['die Richtlinie','die','die Richtlinien','guideline','Die Richtlinie ist zu beachten.','noun','Professional communication','b2;top1'],
['die Weisung','die','die Weisungen','instruction','Die Weisung ist bindend.','noun','Professional communication','b2;top1'],
['die Rückmeldung','die','die Rückmeldungen','feedback','Ich warte auf Rückmeldung.','noun','Professional communication','b2;top1'],
['die Beschwerde','die','die Beschwerden','complaint','Die Beschwerde wurde bearbeitet.','noun','Professional communication','b2;top1'],
['die Unterschrift','die','die Unterschriften','signature','Die Unterschrift fehlt noch.','noun','Professional communication','b2;top1'],
['die Vorlage','die','die Vorlagen','template','Die Vorlage ist fertig.','noun','Professional communication','b2;top1'],
['die Mitteilung','die','die Mitteilungen','notification','Die Mitteilung kam per Mail.','noun','Professional communication','b2;top1'],
['der Anhang','der','die Anhänge','attachment','Der Anhang enthält die Datei.','noun','Professional communication','b2;top1'],
['die Absage','die','die Absagen','rejection','Die Absage kam heute.','noun','Professional communication','b2;top1'],
['die Zusage','die','die Zusagen','acceptance','Die Zusage ist da.','noun','Professional communication','b2;top1'],
['die Anfrage','die','die Anfragen','inquiry','Die Anfrage wurde beantwortet.','noun','Professional communication','b2;top1'],
['das Angebot','das','die Angebote','offer','Das Angebot ist gültig.','noun','Professional communication','b2;top1'],
['die Aufforderung','die','die Aufforderungen','request','Die Aufforderung kam per Post.','noun','Professional communication','b2;top1'],
['die Ablehnung','die','die Ablehnungen','refusal','Die Ablehnung wurde begründet.','noun','Professional communication','b2;top1'],
['die Stellungnahme','die','die Stellungnahmen','statement','Die Stellungnahme ist fällig.','noun','Professional communication','b2;top1'],
['die Zuständigkeit','die','die Zuständigkeiten','responsibility','Die Zuständigkeit liegt bei mir.','noun','Professional communication','b2;top1'],
['der Verteiler','der','die Verteiler','distribution list','Der Verteiler ist aktuell.','noun','Professional communication','b2;top1'],
['die Beauftragung','die','die Beauftragungen','assignment','Die Beauftragung erfolgte schriftlich.','noun','Professional communication','b2;top1'],
]);

add([ // 2. Work and Professional (25)
['die Gehaltserhöhung','die','die Gehaltserhöhungen','salary incr.','Die Gehaltserhöhung wurde beantragt.','noun','Work and professional','b2;top2'],
['die Arbeitsumgebung','die','die Arbeitsumgebungen','work environ.','Die Arbeitsumgebung verbessert sich.','noun','Work and professional','b2;top2'],
['der Arbeitgeber','der','die Arbeitgeber','employer','Der Arbeitgeber zahlt gut.','noun','Work and professional','b2;top2'],
['der Arbeitnehmer','der','die Arbeitnehmer','employee','Der Arbeitnehmer hat Rechte.','noun','Work and professional','b2;top2'],
['die Betriebsvereinbarung','die','die Betriebsvereinbarungen','works agreement','Die Vereinbarung regelt die Pausen.','noun','Work and professional','b2;top2'],
['das Vorstellungsgespräch','das','die Vorstellungsgespräche','job interview','Das Gespräch verlief positiv.','noun','Work and professional','b2;top2'],
['die Stellenausschreibung','die','die Stellenausschreibungen','job posting','Die Ausschreibung ist online.','noun','Work and professional','b2;top2'],
['der Lebenslauf','der','die Lebensläufe','CV','Der Lebenslauf ist aktuell.','noun','Work and professional','b2;top2'],
['das Anschreiben','das','die Anschreiben','cover letter','Das Anschreiben ist wichtig.','noun','Work and professional','b2;top2'],
['die Probezeit','die','die Probezeiten','probation','Die Probezeit dauert 6 Monate.','noun','Work and professional','b2;top2'],
['die Befristung','die','die Befristungen','fixed term','Die Befristung ist zulässig.','noun','Work and professional','b2;top2'],
['das Gehalt','das','die Gehälter','salary','Das Gehalt wird überwiesen.','noun','Work and professional','b2;top2'],
['die Überstunde','die','die Überstunden','overtime','Überstunden werden vergütet.','noun','Work and professional','b2;top2'],
['der Arbeitsschutz','der','','occupational safety','Der Arbeitsschutz hat Priorität.','noun','Work and professional','b2;top2'],
['die Gewerkschaft','die','die Gewerkschaften','trade union','Die Gewerkschaft verhandelt.','noun','Work and professional','b2;top2'],
['der Tarifvertrag','der','die Tarifverträge','collective agr.','Der Tarifvertrag gilt für alle.','noun','Work and professional','b2;top2'],
['die Sozialleistung','die','die Sozialleistungen','social benefit','Sozialleistungen sind wichtig.','noun','Work and professional','b2;top2'],
['der Ausbildungsplatz','der','die Ausbildungsplätze','training pos.','Der Platz ist noch frei.','noun','Work and professional','b2;top2'],
['die Personalabteilung','die','die Personalabteilungen','HR department','Die Personalabteilung hilft.','noun','Work and professional','b2;top2'],
['die Einstellung','die','die Einstellungen','hiring','Die Einstellung ist geplant.','noun','Work and professional','b2;top2'],
['die Entlassung','die','die Entlassungen','dismissal','Die Entlassung war betriebsbedingt.','noun','Work and professional','b2;top2'],
['die Kündigungsfrist','die','die Kündigungsfristen','notice period','Die Frist beträgt drei Monate.','noun','Work and professional','b2;top2'],
['das Arbeitszeugnis','das','die Arbeitszeugnisse','reference','Das Zeugnis ist sehr gut.','noun','Work and professional','b2;top2'],
['die Bewerbung','die','die Bewerbungen','application','Die Bewerbung ist vollständig.','noun','Work and professional','b2;top2'],
['die Kündigung','die','die Kündigungen','termination','Die Kündigung muss schriftlich sein.','noun','Work and professional','b2;top2'],
]);

add([ // 3. Technology and Digital Life (25)
['die Verschlüsselung','die','die Verschlüsselungen','encryption','Die Verschlüsselung schützt Daten.','noun','Technology','b2;top3'],
['die Schnittstelle','die','die Schnittstellen','interface','Die Schnittstelle verbindet Systeme.','noun','Technology','b2;top3'],
['die Programmiersprache','die','die Programmiersprachen','programming lang.','Python ist eine Programmiersprache.','noun','Technology','b2;top3'],
['die Anwendung','die','die Anwendungen','application','Die Anwendung läuft stabil.','noun','Technology','b2;top3'],
['die Firewall','die','die Firewalls','firewall','Die Firewall blockiert Angriffe.','noun','Technology','b2;top3'],
['der Speicherplatz','der','die Speicherplätze','storage space','Der Speicherplatz reicht nicht.','noun','Technology','b2;top3'],
['die Aktualisierung','die','die Aktualisierungen','update','Die Aktualisierung ist fertig.','noun','Technology','b2;top3'],
['das Passwort','das','die Passwörter','password','Das Passwort wurde geändert.','noun','Technology','b2;top3'],
['der Benutzername','der','die Benutzernamen','username','Der Name ist vergeben.','noun','Technology','b2;top3'],
['die Suchmaschine','die','die Suchmaschinen','search engine','Google ist eine Suchmaschine.','noun','Technology','b2;top3'],
['die Datenbank','die','die Datenbanken','database','Die Datenbank ist aktualisiert.','noun','Technology','b2;top3'],
['das Betriebssystem','das','die Betriebssysteme','operating system','Windows ist ein Betriebssystem.','noun','Technology','b2;top3'],
['die Fehlermeldung','die','die Fehlermeldungen','error message','Die Meldung erscheint beim Start.','noun','Technology','b2;top3'],
['die Installation','die','die Installationen','installation','Die Installation ist einfach.','noun','Technology','b2;top3'],
['das Netzwerk','das','die Netzwerke','network','Das Netzwerk ist schnell.','noun','Technology','b2;top3'],
['die Authentifizierung','die','die Authentifizierungen','authentication','Die Authentifizierung ist erforderlich.','noun','Technology','b2;top3'],
['der Algorithmus','der','die Algorithmen','algorithm','Der Algorithmus ist effizient.','noun','Technology','b2;top3'],
['die Cloud','die','','cloud','Die Daten sind in der Cloud.','noun','Technology','b2;top3'],
['die Sicherheitslücke','die','die Sicherheitslücken','security gap','Die Lücke wurde geschlossen.','noun','Technology','b2;top3'],
['der Datenschutz','der','','data protection','Datenschutz ist wichtig.','noun','Technology','b2;top3'],
['die Softwarelizenz','die','die Softwarelizenzen','software license','Die Lizenz ist abgelaufen.','noun','Technology','b2;top3'],
['die Tastatur','die','die Tastaturen','keyboard','Die Tastatur ist kabellos.','noun','Technology','b2;top3'],
['der Bildschirm','der','die Bildschirme','screen','Der Bildschirm ist groß.','noun','Technology','b2;top3'],
['der Browser','der','die Browser','browser','Der Browser ist aktuell.','noun','Technology','b2;top3'],
['die E-Mail-Adresse','die','die E-Mail-Adressen','email address','Bitte geben Sie Ihre Adresse an.','noun','Technology','b2;top3'],
]);

add([ // 4. Healthcare (25)
['die Diagnose','die','die Diagnosen','diagnosis','Die Diagnose wurde bestätigt.','noun','Healthcare','b2;top4'],
['die Behandlung','die','die Behandlungen','treatment','Die Behandlung beginnt bald.','noun','Healthcare','b2;top4'],
['der Blutdruck','der','','blood pressure','Der Blutdruck ist normal.','noun','Healthcare','b2;top4'],
['die Blutprobe','die','die Blutproben','blood sample','Die Probe wird untersucht.','noun','Healthcare','b2;top4'],
['die Impfung','die','die Impfungen','vaccination','Die Impfung schützt.','noun','Healthcare','b2;top4'],
['die Operation','die','die Operationen','surgery','Die OP war erfolgreich.','noun','Healthcare','b2;top4'],
['die Untersuchung','die','die Untersuchungen','examination','Die Untersuchung dauert 30 Min.','noun','Healthcare','b2;top4'],
['der Facharzt','der','die Fachärzte','specialist','Der Facharzt wurde überwiesen.','noun','Healthcare','b2;top4'],
['das Rezept','das','die Rezepte','prescription','Das Rezept ist ausgestellt.','noun','Healthcare','b2;top4'],
['die Krankenakte','die','die Krankenakten','medical record','Die Akte ist vertraulich.','noun','Healthcare','b2;top4'],
['die Wunde','die','die Wunden','wound','Die Wunde heilt gut.','noun','Healthcare','b2;top4'],
['die Vorsorge','die','','preventive care','Vorsorge ist wichtig.','noun','Healthcare','b2;top4'],
['die Therapie','die','die Therapien','therapy','Die Therapie hilft.','noun','Healthcare','b2;top4'],
['stationär','','','inpatient','Der Patient wird stationär aufgenommen.','adjective','Healthcare','b2;top4'],
['ambulant','','','outpatient','Die Behandlung ist ambulant.','adjective','Healthcare','b2;top4'],
['die Nachsorge','die','','aftercare','Nachsorge ist nötig.','noun','Healthcare','b2;top4'],
['der Impfstoff','der','die Impfstoffe','vaccine','Der Impfstoff ist verfügbar.','noun','Healthcare','b2;top4'],
['der Befund','der','die Befunde','finding','Der Befund liegt vor.','noun','Healthcare','b2;top4'],
['die Nebenwirkung','die','die Nebenwirkungen','side effect','Nebenwirkungen sind selten.','noun','Healthcare','b2;top4'],
['chronisch','','','chronic','Die Erkrankung ist chronisch.','adjective','Healthcare','b2;top4'],
['die Überweisung','die','die Überweisungen','referral','Die Überweisung ist ausgestellt.','noun','Healthcare','b2;top4'],
['die Krankheit','die','die Krankheiten','illness','Die Krankheit heilt aus.','noun','Healthcare','b2;top4'],
['der Arzttermin','der','die Arzttermine','appointment','Der Termin ist um zehn.','noun','Healthcare','b2;top4'],
['die Vorsorgeuntersuchung','die','die Vorsorgeuntersuchungen','check-up','Die Untersuchung ist jährlich.','noun','Healthcare','b2;top4'],
['die Notaufnahme','die','die Notaufnahmen','emergency room','Die Notaufnahme ist voll.','noun','Healthcare','b2;top4'],
]);

add([ // 5. Environment and Climate (25)
['die Umweltverschmutzung','die','','pollution','Die Verschmutzung nimmt zu.','noun','Environment','b2;top5'],
['der Klimawandel','der','','climate change','Der Klimawandel ist real.','noun','Environment','b2;top5'],
['die Erderwärmung','die','','global warming','Die Erderwärmung schreitet voran.','noun','Environment','b2;top5'],
['die Nachhaltigkeit','die','','sustainability','Nachhaltigkeit ist wichtig.','noun','Environment','b2;top5'],
['die Solarenergie','die','','solar energy','Solarenergie ist sauber.','noun','Environment','b2;top5'],
['die Windkraft','die','','wind power','Windkraft erzeugt Strom.','noun','Environment','b2;top5'],
['das Ökosystem','das','die Ökosysteme','ecosystem','Das Ökosystem ist bedroht.','noun','Environment','b2;top5'],
['die Artenvielfalt','die','','biodiversity','Die Artenvielfalt nimmt ab.','noun','Environment','b2;top5'],
['der Treibhauseffekt','der','','greenhouse effect','Der Effekt wird verstärkt.','noun','Environment','b2;top5'],
['die Mülltrennung','die','','waste separation','Mülltrennung ist Pflicht.','noun','Environment','b2;top5'],
['der Recyclinghof','der','die Recyclinghöfe','recycling center','Der Hof nimmt Elektroschrott an.','noun','Environment','b2;top5'],
['die Luftverschmutzung','die','','air pollution','Die Luft ist verschmutzt.','noun','Environment','b2;top5'],
['die Abgase','die','','exhaust fumes','Abgase belasten die Luft.','noun','Environment','b2;top5'],
['der Umweltschutz','der','','environmental protection','Umweltschutz ist wichtig.','noun','Environment','b2;top5'],
['ressourcenschonend','','','resource-efficient','Das Verfahren ist ressourcenschonend.','adjective','Environment','b2;top5'],
['der CO2-Ausstoß','der','','CO2 emissions','Der Ausstoß muss sinken.','noun','Environment','b2;top5'],
['ökologisch','','','ecological','Ökologische Landwirtschaft ist besser.','adjective','Environment','b2;top5'],
['die Kläranlage','die','die Kläranlagen','sewage plant','Die Anlage reinigt das Wasser.','noun','Environment','b2;top5'],
['emissionsfrei','','','emission-free','Das Auto fährt emissionsfrei.','adjective','Environment','b2;top5'],
['der Artenschutz','der','','species protection','Artenschutz ist nötig.','noun','Environment','b2;top5'],
['die Umweltpolitik','die','','environmental policy','Die Politik wurde kritisiert.','noun','Environment','b2;top5'],
['der Klimaschutz','der','','climate protection','Klimaschutz geht uns alle an.','noun','Environment','b2;top5'],
['die Müllvermeidung','die','','waste prevention','Müllvermeidung ist am besten.','noun','Environment','b2;top5'],
['die Umweltbelastung','die','','environmental burden','Die Belastung ist zu hoch.','noun','Environment','b2;top5'],
['die Erneuerbare','die','','renewable energy','Erneuerbare sind die Zukunft.','noun','Environment','b2;top5'],
]);

add([ // 6. Law and Consumer Rights (25)
['das Gericht','das','die Gerichte','court','Das Gericht entscheidet.','noun','Law','b2;top6'],
['das Urteil','das','die Urteile','verdict','Das Urteil ist gefallen.','noun','Law','b2;top6'],
['der Kläger','der','die Kläger','plaintiff','Der Kläger fordert Schadenersatz.','noun','Law','b2;top6'],
['die Klage','die','die Klagen','lawsuit','Die Klage wurde eingereicht.','noun','Law','b2;top6'],
['der Vertragsbruch','der','die Vertragsbrüche','breach of contract','Der Bruch hatte Folgen.','noun','Law','b2;top6'],
['das Grundgesetz','das','','Basic Law','Das Grundgesetz schützt Rechte.','noun','Law','b2;top6'],
['die Verfassung','die','die Verfassungen','constitution','Die Verfassung garantiert Freiheit.','noun','Law','b2;top6'],
['die Verordnung','die','die Verordnungen','regulation','Die Verordnung trat in Kraft.','noun','Law','b2;top6'],
['die Gewährleistung','die','','warranty','Die Garantie gilt zwei Jahre.','noun','Law','b2;top6'],
['das Widerrufsrecht','das','','right of withdrawal','Das Recht gilt 14 Tage.','noun','Law','b2;top6'],
['die Rechnung','die','die Rechnungen','invoice','Die Rechnung ist bezahlt.','noun','Law','b2;top6'],
['der Kaufvertrag','der','die Kaufverträge','purchase contract','Der Vertrag ist unterschrieben.','noun','Law','b2;top6'],
['die Mietkaution','die','die Mietkautionen','security deposit','Die Kaution wird zurückgezahlt.','noun','Law','b2;top6'],
['rechtlich','','','legal','Rechtlich ist das in Ordnung.','adjective','Law','b2;top6'],
['anfechten','','','to contest','Er ficht die Entscheidung an.','verb','Law','b2;top6'],
['verklagen','','','to sue','Er verklagt die Firma.','verb','Law','b2;top6'],
['die Straftat','die','die Straftaten','criminal offense','Die Tat wurde gemeldet.','noun','Law','b2;top6'],
['die Ermittlung','die','die Ermittlungen','investigation','Die Ermittlungen laufen.','noun','Law','b2;top6'],
['der Tatverdächtige','der','die Tatverdächtigen','suspect','Der Verdächtige wurde befragt.','noun','Law','b2;top6'],
['der Rechtsanwalt','der','die Rechtsanwälte','lawyer','Der Anwalt berät mich.','noun','Law','b2;top6'],
['der Vertrag','der','die Verträge','contract','Der Vertrag läuft aus.','noun','Law','b2;top6'],
['die Schadensersatzforderung','die','die Schadensersatzforderungen','damages claim','Die Forderung beträgt 5000 Euro.','noun','Law','b2;top6'],
['die Ordnungswidrigkeit','die','die Ordnungswidrigkeiten','admin. offense','Die Ordnungswidrigkeit wird bestraft.','noun','Law','b2;top6'],
['die Fahrerlaubnis','die','die Fahrerlaubnisse','driving license','Die Fahrerlaubnis wurde entzogen.','noun','Law','b2;top6'],
['die Durchsetzung','die','','enforcement','Die Durchsetzung erfolgt vor Gericht.','noun','Law','b2;top6'],
]);

add([ // 7. Economy and Business (25)
['der Aktienkurs','der','die Aktienkurse','stock price','Der Kurs ist gestiegen.','noun','Economy','b2;top7'],
['die Inflation','die','','inflation','Die Inflation steigt.','noun','Economy','b2;top7'],
['der Zinssatz','der','die Zinssätze','interest rate','Der Satz beträgt drei Prozent.','noun','Economy','b2;top7'],
['die Investition','die','die Investitionen','investment','Die Investition lohnt sich.','noun','Economy','b2;top7'],
['der Gewinn','der','die Gewinne','profit','Der Gewinn stieg.','noun','Economy','b2;top7'],
['der Verlust','der','die Verluste','loss','Der Verlust ist hoch.','noun','Economy','b2;top7'],
['die Bilanz','die','die Bilanzen','balance sheet','Die Bilanz ist positiv.','noun','Economy','b2;top7'],
['der Umsatz','der','die Umsätze','revenue','Der Umsatz wuchs.','noun','Economy','b2;top7'],
['die Dividende','die','die Dividenden','dividend','Die Dividende wird ausgezahlt.','noun','Economy','b2;top7'],
['der Finanzmarkt','der','die Finanzmärkte','financial market','Der Markt reagiert.','noun','Economy','b2;top7'],
['die Währung','die','die Währungen','currency','Der Euro ist die Währung.','noun','Economy','b2;top7'],
['der Wechselkurs','der','die Wechselkurse','exchange rate','Der Kurs schwankt.','noun','Economy','b2;top7'],
['die Subvention','die','die Subventionen','subsidy','Die Subvention wurde bewilligt.','noun','Economy','b2;top7'],
['der Marktanteil','der','die Marktanteile','market share','Der Anteil beträgt 25%.','noun','Economy','b2;top7'],
['die Wettbewerbsfähigkeit','die','','competitiveness','Die Fähigkeit muss gestärkt werden.','noun','Economy','b2;top7'],
['die Globalisierung','die','','globalization','Die Globalisierung schreitet voran.','noun','Economy','b2;top7'],
['der Auftrag','der','die Aufträge','order','Der Auftrag wurde geliefert.','noun','Economy','b2;top7'],
['der Unternehmer','der','die Unternehmer','entrepreneur','Der Unternehmer gründete eine Firma.','noun','Economy','b2;top7'],
['das Eigenkapital','das','','equity capital','Das Kapital beträgt eine Million.','noun','Economy','b2;top7'],
['die Konjunktur','die','','economic cycle','Die Konjunktur erholt sich.','noun','Economy','b2;top7'],
['die Steuererklärung','die','die Steuererklärungen','tax return','Die Erklärung muss abgegeben werden.','noun','Economy','b2;top7'],
['die Aktie','die','die Aktien','stock','Die Aktie fällt.','noun','Economy','b2;top7'],
['der Börsengang','der','die Börsengänge','IPO','Der Börsengang war erfolgreich.','noun','Economy','b2;top7'],
['die Lieferkette','die','die Lieferketten','supply chain','Die Kette wurde unterbrochen.','noun','Economy','b2;top7'],
['das BIP','das','','GDP','Das BIP ist gestiegen.','noun','Economy','b2;top7'],
]);

add([ // 8. Education and Learning (25)
['die Vorlesung','die','die Vorlesungen','lecture','Die Vorlesung beginnt.','noun','Education','b2;top8'],
['das Seminar','das','die Seminare','seminar','Das Seminar findet donnerstags statt.','noun','Education','b2;top8'],
['die Prüfung','die','die Prüfungen','exam','Die Prüfung ist schwer.','noun','Education','b2;top8'],
['der Studiengang','der','die Studiengänge','degree program','Der Studiengang dauert 6 Semester.','noun','Education','b2;top8'],
['die Abschlussarbeit','die','die Abschlussarbeiten','thesis','Die Arbeit wird benotet.','noun','Education','b2;top8'],
['der Dozent','der','die Dozenten','lecturer','Der Dozent erklärt den Stoff.','noun','Education','b2;top8'],
['die Einschreibung','die','die Einschreibungen','enrollment','Die Einschreibung beginnt im August.','noun','Education','b2;top8'],
['das Stipendium','das','die Stipendien','scholarship','Das Stipendium deckt die Kosten.','noun','Education','b2;top8'],
['die Forschung','die','','research','Die Forschung wird gefördert.','noun','Education','b2;top8'],
['die Studiengebühr','die','die Studiengebühren','tuition fee','Die Gebühren sind hoch.','noun','Education','b2;top8'],
['das Praktikum','das','die Praktika','internship','Das Praktikum dauert drei Monate.','noun','Education','b2;top8'],
['das Auslandssemester','das','','semester abroad','Das Semester war toll.','noun','Education','b2;top8'],
['die Studienordnung','die','die Studienordnungen','study regs.','Die Ordnung regelt den Ablauf.','noun','Education','b2;top8'],
['die Prüfungsordnung','die','die Prüfungsordnungen','exam regs.','Die Ordnung ist online.','noun','Education','b2;top8'],
['die Immatrikulation','die','','matriculation','Die Immatrikulation ist erfolgt.','noun','Education','b2;top8'],
['das Studienfach','das','die Studienfächer','subject','Mein Fach ist Medizin.','noun','Education','b2;top8'],
['die Hausarbeit','die','die Hausarbeiten','term paper','Die Arbeit ist abgegeben.','noun','Education','b2;top8'],
['das Tutorium','das','die Tutorien','tutorial','Das Tutorium hilft beim Lernen.','noun','Education','b2;top8'],
['die Bibliothek','die','die Bibliotheken','library','Die Bibliothek hat viele Bücher.','noun','Education','b2;top8'],
['der Semesterbeitrag','der','die Semesterbeiträge','semester fee','Der Beitrag ist fällig.','noun','Education','b2;top8'],
['die Voraussetzung','die','die Voraussetzungen','prerequisite','Die Voraussetzung ist erfüllt.','noun','Education','b2;top8'],
['die Note','die','die Noten','grade','Die Note ist gut.','noun','Education','b2;top8'],
['die Exmatrikulation','die','','exmatriculation','Die Exmatrikulation ist zum Semesterende.','noun','Education','b2;top8'],
['das Semesterticket','das','die Semestertickets','transit pass','Das Ticket gilt im ganzen Land.','noun','Education','b2;top8'],
['die Leistungsbewertung','die','die Leistungsbewertungen','assessment','Die Bewertung ist fair.','noun','Education','b2;top8'],
]);

add([ // 9. Media and Communication (25)
['die Berichterstattung','die','','reporting','Die Berichterstattung ist ausgewogen.','noun','Media','b2;top9'],
['der Journalist','der','die Journalisten','journalist','Der Journalist recherchiert.','noun','Media','b2;top9'],
['die Schlagzeile','die','die Schlagzeilen','headline','Die Schlagzeile ist reißerisch.','noun','Media','b2;top9'],
['die Pressemitteilung','die','die Pressemitteilungen','press release','Die PM wurde veröffentlicht.','noun','Media','b2;top9'],
['der Sender','der','die Sender','broadcaster','Der Sender zeigt Nachrichten.','noun','Media','b2;top9'],
['die Reportage','die','die Reportagen','report','Die Reportage war interessant.','noun','Media','b2;top9'],
['das Interview','das','die Interviews','interview','Das Interview wurde aufgezeichnet.','noun','Media','b2;top9'],
['die Auflage','die','die Auflagen','circulation','Die Auflage sinkt.','noun','Media','b2;top9'],
['die Öffentlichkeit','die','','public','Die Öffentlichkeit wurde informiert.','noun','Media','b2;top9'],
['die Einschaltquote','die','die Einschaltquoten','ratings','Die Quote ist hoch.','noun','Media','b2;top9'],
['das Medium','das','die Medien','medium','Das Medium berichtet objektiv.','noun','Media','b2;top9'],
['die Redaktion','die','die Redaktionen','editorial team','Die Redaktion arbeitet rund um die Uhr.','noun','Media','b2;top9'],
['die Zeitschrift','die','die Zeitschriften','magazine','Die Zeitschrift erscheint monatlich.','noun','Media','b2;top9'],
['die Tageszeitung','die','die Tageszeitungen','daily newspaper','Die Zeitung kommt jeden Morgen.','noun','Media','b2;top9'],
['die Werbung','die','die Werbungen','advertisement','Die Werbung läuft im Fernsehen.','noun','Media','b2;top9'],
['die Anzeige','die','die Anzeigen','ad','Die Anzeige stand in der Zeitung.','noun','Media','b2;top9'],
['die Übertragung','die','die Übertragungen','broadcast','Die Übertragung beginnt um 20 Uhr.','noun','Media','b2;top9'],
['der Moderator','der','die Moderatoren','host','Der Moderator führt durch die Sendung.','noun','Media','b2;top9'],
['die Kolumne','die','die Kolumnen','column','Die Kolumne erscheint wöchentlich.