import json, sys

vocab = []

def add(id, word, article, plural, translation, lay, example, ex_tr, patient, doc, category, tags):
    vocab.append({
        "id": id, "level": "FSP", "word": word,
        "article": article, "plural": plural, "translation": translation,
        "layExplanation": lay, "example": example, "exampleTranslation": ex_tr,
        "patientFriendlyPhrase": patient, "doctorToDoctorPhrase": doc,
        "category": category, "tags": tags
    })

# 1-10: General Hospital
add("fsp_v_1","die Aufnahme","die",None,"admission","Wenn ein Patient ins Krankenhaus kommt und offiziell aufgenommen wird.","Der Patient wurde gestern zur Aufnahme in die Klinik gebracht.","The patient was brought to the hospital for admission yesterday.","Sie werden jetzt aufgenommen. Sie bekommen ein Zimmer und wir kummern uns um Sie.","Die Aufnahme erfolgte um 14 Uhr uber die Notaufnahme.","General Hospital",["hospital","admission"])
add("fsp_v_2","die Entlassung","die","die Entlassungen","discharge","Wenn der Patient das Krankenhaus wieder verlassen darf.","Die Entlassung ist fur morgen fruh geplant.","The discharge is planned for tomorrow morning.","Sie konnen morgen nach Hause. Wir besprechen vorher noch alles Wichtige.","Entlassung in die hausliche Versorgung bei stabiler Kreislaufsituation.","General Hospital",["hospital","discharge"])
add("fsp_v_3","die Visite","die","die Visiten","rounds","Der tagliche Besuch des Arztes am Patientenbett.","Die Visite beginnt jeden Morgen um 8 Uhr.","Rounds begin every morning at 8 o'clock.","Guten Morgen, wir machen jetzt Visite. Ich schaue kurz, wie es Ihnen geht.","Bei der Visite zeigte sich der Patient kreislaufstabil.","General Hospital",["hospital","rounds"])
add("fsp_v_4","der Aufnahmebefund","der","die Aufnahmebefunde","admission findings","Die erste Untersuchung und der Zustand des Patienten bei der Aufnahme.","Der Aufnahmebefund zeigte einen erhohten Blutdruck.","The admission findings showed elevated blood pressure.","Wir haben bei Ihrer Aufnahme alles untersucht und dokumentiert.","Aufnahmebefund: 45-jahriger Patient mit akutem Thoraxschmerz.","General Hospital",["hospital","admission"])
add("fsp_v_5","die Verlegung","die","die Verlegungen","transfer","Wenn ein Patient in eine andere Abteilung oder ein anderes Krankenhaus gebracht wird.","Die Verlegung auf die Intensivstation war notwendig.","The transfer to the ICU was necessary.","Wir verlegen Sie auf die Intensivstation, wo wir Sie besser uberwachen konnen.","Bei Verschlechterung Verlegung auf ITS erwogen.","General Hospital",["hospital","transfer"])

# 6-15: Anamnesis
add("fsp_v_6","die Anamnese","die","die Anamnesen","medical history","Das Gesprach, bei dem der Arzt die Krankengeschichte des Patienten erfragt.","Zunachst erhebe ich Ihre Anamnese, also Ihre Krankengeschichte.","First I will take your history.","Ich mochte Ihnen jetzt ein paar Fragen zu Ihrer Gesundheit stellen.","Anamnese: Typische Angina-pectoris-Symptomatik seit 3 Tagen.","Anamnesis",["history","anamnesis"])
add("fsp_v_7","die Eigenanamnese","die","die Eigenanamnesen","patient's own history","Die Krankengeschichte, die der Patient selbst berichtet.","In der Eigenanamnese gab der Patient Asthma an.","In his own history, the patient reported asthma.","Hatten Sie fruher schon einmal gesundheitliche Probleme?","Eigenanamnese: Asthma bronchiale seit Kindheit.","Anamnesis",["history"])
add("fsp_v_8","die Familienanamnese","die","die Familienanamnesen","family history","Informationen uber Krankheiten in der Familie des Patienten.","Die Familienanamnese ergab mehrere Herzinfarkte beim Vater.","The family history revealed several heart attacks in the father.","Gibt es in Ihrer Familie Erkrankungen wie Herzinfarkt oder Diabetes?","Familienanamnese: kardiovaskulare Erkrankungen beim Vater bekannt.","Anamnesis",["family","history"])
add("fsp_v_9","die Sozialanamnese","die",None,"social history","Informationen uber Beruf, Lebensumstande und Gewohnheiten des Patienten.","Die Sozialanamnese ergab starke berufliche Belastung.","The social history revealed high occupational stress.","Darf ich fragen, was Sie beruflich machen und wie Sie leben?","Sozialanamnese: Schichtarbeiter, starker Nikotinkonsum.","Anamnesis",["social","history"])
add("fsp_v_10","der Ausloser","der","die Ausloser","trigger","Das Ereignis, das die Beschwerden gestartet hat.","Der Ausloser der Schmerzen war schweres Heben.","The trigger of the pain was heavy lifting.","Gab es etwas Bestimmtes, das die Schmerzen ausgelost hat?","Als Ausloser wurde schweres Heben angegeben.","Anamnesis",["anamnesis","trigger"])
add("fsp_v_11","die Hauptbeschwerde","die","die Hauptbeschwerden","chief complaint","Das wichtigste Symptom, mit dem der Patient zum Arzt kommt.","Die Hauptbeschwerde sind Brustschmerzen seit 2 Stunden.","The chief complaint is chest pain for 2 hours.","Was ist Ihr Hauptproblem? Weshalb sind Sie heute zu mir gekommen?","Hauptbeschwerde: retrosternales Druckgefuhl seit 2 Stunden.","Anamnesis",["anamnesis","complaint"])
add("fsp_v_12","der Beginn","der",None,"onset","Der Zeitpunkt, zu dem die Beschwerden angefangen haben.","Der Beginn der Symptome liegt etwa 3 Tage zuruck.","The onset of symptoms was about 3 days ago.","Wann haben die Beschwerden genau angefangen?","Beginn der Symptomatik vor 72 Stunden.","Anamnesis",["anamnesis","timing"])
add("fsp_v_13","der Verlauf","der","die Verlaufe","course / progression","Wie sich die Beschwerden seit dem Beginn entwickelt haben.","Der Verlauf war langsam fortschreitend.","The course was slowly progressive.","Haben sich die Beschwerden verschlimmert oder sind sie gleich geblieben?","Progredienter Verlauf der Dyspnoe in den letzten Wochen.","Anamnesis",["anamnesis","course"])
add("fsp_v_14","die Begleitsymptome","die",None,"accompanying symptoms","Andere Symptome, die zusammen mit der Hauptbeschwerde aufgetreten sind.","Als Begleitsymptome traten Übelkeit und Schwindel auf.","Nausea and dizziness occurred as accompanying symptoms.","Hatten Sie noch andere Beschwerden gleichzeitig?","Begleitsymptome: Übelkeit, kalter Schweiß.","Anamnesis",["anamnesis","symptoms"])
add("fsp_v_15","die Verschlimmerung","die","die Verschlimmerungen","exacerbation","Wenn sich die Beschwerden plotzlich stark verschlechtern.","Bei Belastung kommt es zur Verschlimmerung der Schmerzen.","Exertion leads to exacerbation of pain.","Wird es schlimmer, wenn Sie sich bewegen oder etwas Bestimmtes tun?","Verschlimmerung der Symptome unter Belastung.","Anamnesis",["anamnesis","exacerbation"])

# 16-25: Symptoms
add("fsp_v_16","das Symptom","das","die Symptome","symptom","Ein Zeichen oder eine Beschwerde, die auf eine Krankheit hinweist.","Die Symptome begannen vor drei Tagen.","The symptoms began three days ago.","Welche Symptome haben Sie genau bemerkt?","Die Symptomatik ist vereinbar mit einem akuten Koronarsyndrom.","Symptoms",["symptom"])
add("fsp_v_17","die Beschwerde","die","die Beschwerden","complaint","Das, was dem Patienten wehtut oder Probleme macht.","Der Patient klagt uber stechende Beschwerden in der Brust.","The patient complains of stabbing discomfort in the chest.","Was fur Beschwerden haben Sie genau?","Hauptbeschwerde: retrosternales Druckgefuhl.","Symptoms",["symptom","complaint"])
add("fsp_v_18","das Krankheitsgefuhl","das",None,"malaise","Allgemeines Gefuhl, krank zu sein, ohne genaue Ursache.","Der Patient berichtet uber ein allgemeines Krankheitsgefuhl seit einer Woche.","The patient reports general malaise for one week.","Fuhlen Sie sich allgemein krank oder haben Sie konkrete Schmerzen?","Allgemeines Krankheitsgefuhl bei subfebrilen Temperaturen.","Symptoms",["symptom","malaise"])
add("fsp_v_19","die Schmerzausstrahlung","die","die Schmerzausstrahlungen","radiation of pain","Wenn der Schmerz von einer Stelle in andere Korperregionen ausstrahlt.","Die Schmerzausstrahlung erfolgt in den linken Arm.","The pain radiates into the left arm.","Strahlten die Schmerzen in andere Korperteile aus?","Schmerzausstrahlung in den linken Arm und Kiefer.","Symptoms",["pain","symptom"])
add("fsp_v_20","der Schweregrad","der","die Schweregrade","severity","Wie stark die Beschwerden sind.","Der Schweregrad der Schmerzen wurde mit 8 von 10 angegeben.","The severity of pain was rated 8 out of 10.","Auf einer Skala von 1 bis 10, wie stark sind die Schmerzen?","Schweregrad der Dyspnoe nach NYHA III.","Symptoms",["severity","symptom"])
add("fsp_v_21","das Fieber","das",None,"fever","Erhohte Korpertemperatur als Zeichen einer Infektion.","Der Patient hat seit gestern Fieber bis 39,5 Grad.","The patient has had fever up to 39.5 degrees since yesterday.","Haben Sie Fieber? Haben Sie schon einmal gemessen?","Fieber bis 39,5 Grad Celsius, kein Schuttelfrost.","Symptoms",["symptom","fever"])
add("fsp_v_22","der Schuttelfrost","der",None,"rigors / chills","Starkes Frieren mit Zittern, oft bei Fieber.","Der Patient berichtet uber Schuttelfrost in der Nacht.","The patient reports chills during the night.","Hatten Sie Schuttelfrost, also starkes Frieren mit Zittern?","Schuttelfrost und Fieber bis 40 Grad.","Symptoms",["symptom","chills"])
add("fsp_v_23","der Nachtschweiß","der",None,"night sweats","Starkes Schwitzen in der Nacht, oft ein Warnsignal.","Nachtschweiß trat in den letzten Wochen mehrfach auf.","Night sweats occurred several times in recent weeks.","Schwitzen Sie nachts stark, sodass die Kleidung nass wird?","Nachtschweiß und Gewichtsverlust in den letzten 3 Monaten.","Symptoms",["symptom","warning"])
add("fsp_v_24","der Gewichtsverlust","der",None,"weight loss","Ungewollte Abnahme des Korpergewichts.","Der Gewichtsverlust betragt ca. 5 kg in 2 Monaten.","Weight loss is about 5 kg in 2 months.","Haben Sie in letzter Zeit ungewollt abgenommen?","Ungewollter Gewichtsverlust von 5 kg in 8 Wochen.","Symptoms",["symptom","weight"])
add("fsp_v_25","die Appetitlosigkeit","die",None,"loss of appetite","Kein Hunger oder kein Verlangen zu essen.","Seit der Erkrankung leidet der Patient unter Appetitlosigkeit.","Since the illness, the patient has suffered from loss of appetite.","Hatten Sie Appetit? Konnen Sie normal essen?","Appetitlosigkeit und Gewichtsverlust.","Symptoms",["symptom","appetite"])

# 26-35: Pain Description
add("fsp_v_26","stechend",None,None,"stabbing","Ein Schmerz, der sich anfuhlt wie ein Stich mit einer Nadel.","Der Patient beschreibt stechende Schmerzen hinter dem Brustbein.","The patient describes stabbing pain behind the sternum.","Fuhlt es sich an wie ein Stechen oder eher wie ein Druck?","Stechende retrosternale Schmerzen, typisch fur Perikarditis.","Pain Description",["pain","quality"])
add("fsp_v_27","dumpf",None,None,"dull","Ein Schmerz, der nicht scharf ist, sondern eher wie ein Druckgefuhl.","Die Kopfschmerzen werden als dumpf und drueckend beschrieben.","The headaches are described as dull and pressing.","Ist der Schmerz eher dumpf und drueckend oder scharf und stechend?","Dumpfe Oberbauchschmerzen, typisch fur eine Pankreatitis.","Pain Description",["pain","quality"])
add("fsp_v_28","kolikartig",None,None,"colicky","Wellenformige Schmerzen, die kommen und gehen.","Die Bauchschmerzen sind kolikartig und treten wellenformig auf.","The abdominal pain is colicky and occurs in waves.","Kommen die Schmerzen in Wellen oder sind sie dauerhaft?","Kolikartige Schmerzen im rechten Unterbauch, Verdacht auf Nierenstein.","Pain Description",["pain","quality"])
add("fsp_v_29","brennend",None,None,"burning","Ein Schmerz, der sich anfuhlt wie ein Brennen.","Der Patient klagt uber brennende Schmerzen in der Speiserohre.","The patient complains of burning pain in the esophagus.","Fuhlt es sich brennend an, zum Beispiel wie Sodbrennen?","Brennende epigastrische Schmerzen, typisch fur Reflux.","Pain Description",["pain","quality"])
add("fsp_v_30","der Druckschmerz","der","die Druckschmerzen","tenderness","Schmerz, der entsteht, wenn man auf eine bestimmte Stelle druckt.","Bei der Untersuchung zeigte sich ein Druckschmerz im rechten Oberbauch.","On examination, tenderness was found in the right upper abdomen.","Tut es weh, wenn ich hier drucke?","Druckschmerz im rechten Oberbauch mit Loslassschmerz.","Pain Description",["pain","tenderness"])
add("fsp_v_31","der Loslassschmerz","der","die Loslassschmerzen","rebound tenderness","Schmerz, der entsteht, wenn man den Druck plotzlich loslasst.","Der Loslassschmerz ist positiv, Hinweis auf Peritonitis.","Rebound tenderness is positive, indicating peritonitis.","Passen Sie auf, ich drucke hier und lasse dann plotzlich los.","Positiver Loslassschmerz im rechten Unterbauch.","Pain Description",["pain","rebound"])
add("fsp_v_32","druckend",None,None,"pressing / squeezing","Ein Schmerz, der sich anfuhlt wie ein starker Druck von außen.","Der Patient beschreibt ein druckendes Gefuhl auf der Brust.","The patient describes a pressing sensation on the chest.","Fuhlt es sich an, als ob etwas auf Ihrer Brust druckt?","Druckender retrosternaler Schmerz, typisch fur Angina pectoris.","Pain Description",["pain","quality"])
add("fsp_v_33","pochend",None,None,"throbbing","Ein Schmerz, der im Rhythmus des Herzschlags kommt und geht.","Der Patient klagt uber pochende Kopfschmerzen.","The patient complains of throbbing headaches.","Pocht der Schmerz oder ist er gleichmassig?","Pochende, einseitige Kopfschmerzen typisch fur Migrane.","Pain Description",["pain","quality"])
add("fsp_v_34","wandernd",None,None,"migrating","Ein Schmerz, der seine Position im Korper andert.","Die Gelenkschmerzen sind wandernd, mal hier, mal dort.","The joint pain is migrating, sometimes here, sometimes there.","Andert der Schmerz seine Position?","Wandernde Gelenkschmerzen, typisch fur rheumatisches Fieber.","Pain Description",["pain","quality"])
add("fsp_v_35","belastungsabhangig",None,None,"exertion-dependent","Schmerzen, die nur bei bestimmten Aktivitaten auftreten.","Die Schmerzen sind belastungsabhangig und lassen in Ruhe nach.","The pain is exertion-dependent and subsides at rest.","Treten die Schmerzen nur bei bestimmten Bewegungen auf?","Belastungsabhangige Knieschmerzen bei bekannter Gonarthrose.","Pain Description",["pain","trigger"])

# 36-45: Cardiovascular
add("fsp_v_36","der Herzinfarkt","der","die Herzinfarkte","heart attack","Wenn ein Blutgefass im Herzen blockiert ist.","Der Patient erlitt einen akuten Herzinfarkt.","The patient suffered an acute heart attack.","Sie haben einen Herzinfarkt. Ein Blutgefass in Ihrem Herzen ist verschlossen.","Akuter ST-Hebungsinfarkt der Vorderwand.","Cardiovascular",["cardio","infarction"])
add("fsp_v_37","die Angina pectoris","die",None,"angina pectoris","Druck- oder Engegefuhl in der Brust durch Sauerstoffmangel im Herzen.","Der Patient klagt uber Angina-pectoris-Beschwerden bei Belastung.","The patient complains of angina symptoms on exertion.","Haben Sie ein Engegefuhl in der Brust, zum Beispiel beim Treppensteigen?","Stabile Angina pectoris CCS II bei bekannter KHK.","Cardiovascular",["cardio","angina"])
add("fsp_v_38","die Herzinsuffizienz","die",None,"heart failure","Das Herz pumpt nicht mehr stark genug.","Der Patient wird wegen einer dekompensierten Herzinsuffizienz stationar aufgenommen.","The patient is admitted for decompensated heart failure.","Ihr Herz pumpt nicht mehr so kraftig, deshalb haben Sie Wasser in den Beinen.","Dekompensierte Herzinsuffizienz bei eingeschrankter LV-Funktion.","Cardiovascular",["cardio","heart failure"])
add("fsp_v_39","der Blutdruck","der","die Blutdruckwerte","blood pressure","Der Druck, mit dem das Blut durch die Arterien stromt.","Der Blutdruck betragt 150/90 mmHg.","The blood pressure is 150/90 mmHg.","Ihr Blutdruck ist etwas hoch. Wir werden das im Auge behalten.","Blutdruck bei Aufnahme 150/90 mmHg.","Cardiovascular",["cardio","vital"])
add("fsp_v_40","die Rhythmusstorung","die","die Rhythmusstorungen","arrhythmia","Wenn das Herz unregelmassig schlagt.","Im EKG zeigte sich eine Rhythmusstorung.","The ECG showed an arrhythmia.","Ihr Herz schlagt manchmal unregelmassig.","Vorhofflimmern mit absoluter Arrhythmie.","Cardiovascular",["cardio","arrhythmia"])
add("fsp_v_41","die Koronare Herzkrankheit","die",None,"coronary artery disease","Verengung der Herzkranzgefasse durch Arteriosklerose.","Der Patient hat eine bekannte koronare Herzkrankheit.","The patient has known coronary artery disease.","Ihre Herzkranzgefasse sind verengt. Das nennt man koronare Herzkrankheit.","KHK mit Dreigefasserkrankung, Z. n. PCI des RIVA.","Cardiovascular",["cardio","cad"])
add("fsp_v_42","der Herzkatheter","der","die Herzkatheter","cardiac catheterization","Eine Untersuchung, bei der ein Schlauch durch die Blutgefasse bis zum Herzen gefuhrt wird.","Morgen ist eine Herzkatheteruntersuchung geplant.","A cardiac catheterization is planned for tomorrow.","Wir schauen morgen mit einem Katheter in Ihre Herzkranzgefasse.","Geplante Koronarangiographie bei Verdacht auf KHK.","Cardiovascular",["cardio","procedure"])
add("fsp_v_43","der Stent","der","die Stents","stent","Ein kleines Metallgeflecht, das verengte Blutgefasse offen halt.","Dem Patienten wurde ein Stent in die linke Herzkranzarterie gesetzt.","A stent was placed in the left coronary artery.","Wir setzen ein kleines Rohrchen ein, das das Gefass offen halt.","Stenteinlage in den RIVA bei hochgradiger Stenose.","Cardiovascular",["cardio","stent"])
add("fsp_v_44","die Herzfrequenz","die","die Herzfrequenzen","heart rate","Die Anzahl der Herzschlage pro Minute.","Die Herzfrequenz liegt bei 85 Schlagen pro Minute.","The heart rate is 85 beats per minute.","Ihr Herz schlagt etwa 85 Mal pro Minute. Das ist normal.","Herzfrequenz 85/min, normofrequent.","Cardiovascular",["cardio","vital"])
add("fsp_v_45","der Blutgerinnsel","das","die Blutgerinnsel","blood clot","Ein verklumpter Blutbestandteil, der ein Gefass verstopfen kann.","Es besteht die Gefahr der Bildung eines Blutgerinnsels.","There is a risk of blood clot formation.","Es kann sich ein Blutklumpen bilden, der das Gefass verstopft.","Thrombusbildung im linken Vorhof bei Vorhofflimmern.","Cardiovascular",["cardio","clot"])

# 46-55: Respiratory
add("fsp_v_46","die Atemnot","die",None,"shortness of breath","Das Gefuhl, nicht genug Luft zu bekommen.","Der Patient leidet seit Tagen unter zunehmender Atemnot.","The patient has progressive shortness of breath.","Haben Sie das Gefuhl, nicht genug Luft zu bekommen?","Ruhedyspnoe bei bekannter COPD GOLD III.","Respiratory",["resp","dyspnea"])
add("fsp_v_47","der Husten","der",None,"cough","Das reflektorische Ausstoen von Luft aus den Atemwegen.","Der Husten besteht seit etwa zwei Wochen.","The cough has been present for about two weeks.","Haben Sie Husten? Kommt etwas dabei hoch?","Produktiver Husten mit gelblichem Auswurf.","Respiratory",["resp","cough"])
add("fsp_v_48","der Auswurf","der",None,"sputum","Das Sekret, das beim Husten aus der Lunge kommt.","Der Auswurf ist gelblich und zah.","The sputum is yellowish and thick.","Kommt beim Husten etwas hoch? Welche Farbe?","Eitriger Auswurf, farblos bis gelblich.","Respiratory",["resp","sputum"])
add("fsp_v_49","die Lungenentzundung","die","die Lungenentzundungen","pneumonia","Eine Entzundung im Lungengewebe.","Die Diagnose lautet Lungenentzundung des rechten Unterlappens.","The diagnosis is pneumonia of the right lower lobe.","Sie haben eine Lungenentzundung, die wir mit Antibiotika behandeln.","Ambulant erworbene Pneumonie des rechten Unterlappens.","Respiratory",["resp","pneumonia"])
add("fsp_v_50","die Sauerstoffsattigung","die","die Sauerstoffsattigungen","oxygen saturation","Der Anteil des Sauerstoffs im Blut.","Die Sauerstoffsattigung betragt 94 Prozent unter Raumluft.","Oxygen saturation is 94 percent on room air.","Ihr Sauerstoffgehalt im Blut ist etwas niedrig.","SpO2 88% unter Raumluft, 2 Liter O2 erforderlich.","Respiratory",["resp","oxygen"])
add("fsp_v_51","die COPD","die",None,"COPD","Chronische Lungenerkrankung mit dauerhaft verengten Atemwegen.","Der Patient hat eine bekannte COPD im Stadium GOLD III.","The patient has known COPD stage GOLD III.","Sie haben eine chronische Lungenerkrankung, die die Atemwege verengt.","COPD GOLD III, Exazerbation bei Infekt.","Respiratory",["resp","copd"])
add("fsp_v_52","das Asthma bronchiale","das",None,"bronchial asthma","Anfallsweise Verengung der Atemwege mit Atemnot.","Der Patient leidet seit Kindheit an Asthma bronchiale.","The patient has suffered from bronchial asthma since childhood.","Bei Asthma verengen sich die Atemwege anfallsartig.","Asthma bronchiale, aktuell kontrolliert unter ICS/LABA.","Respiratory",["resp","asthma"])
add("fsp_v_53","die Bronchitis","die","die Bronchitiden","bronchitis","Entzundung der Bronchien, oft mit Husten verbunden.","Der Patient hat eine akute Bronchitis mit produktivem Husten.","The patient has acute bronchitis with productive cough.","Sie haben eine Bronchitis, eine Entzundung Ihrer Atemwege.","Akute obstruktive Bronchitis bei bekannter Hyperreagibilitat.","Respiratory",["resp","bronchitis"])
add("fsp_v_54","die Lungenembolie","die","die Lungenembolien","pulmonary embolism","Wenn ein Blutgerinnsel ein Lungengefass verstopft.","Der Patient wurde mit Verdacht auf Lungenembolie eingeliefert.","The patient was admitted with suspected pulmonary embolism.","Ein Blutgerinnsel ist in ein Lungengefass gewandert und hat es verstopft.","Akute Lungenembolie mit Rechtsherzbelastung im Echo.","Respiratory",["resp","embolism"])
add("fsp_v_55","die Lungenfibrose","die","die Lungenfibrosen","pulmonary fibrosis","Vernarbung des Lungengewebes mit zunehmender Atemnot.","Die Lungenfibrose ist durch eine langsame Verschlechterung gekennzeichnet.","Pulmonary fibrosis is characterized by slow deterioration.","Das Lungengewebe vernarbt zunehmend, was die Atmung erschwert.","Idiopathische Lungenfibrose mit restriktiver Ventilationsstorung.","Respiratory",["resp","fibrosis"])

# 56-65: Gastrointestinal
add("fsp_v_56","die Übelkeit","die",None,"nausea","Das Gefuhl, sich ubergeben zu mussen.","Der Patient klagt uber starke Übelkeit nach dem Essen.","The patient complains of severe nausea after eating.","Ist Ihnen übel? Mussen Sie sich ubergeben?","Postprandiale Übelkeit ohne Erbrechen.","Gastrointestinal",["gi","nausea"])
add("fsp_v_57","das Erbrechen","das",None,"vomiting","Wenn der Mageninhalt durch den Mund wieder herauskommt.","Das Erbrechen trat mehrmals taglich auf.","Vomiting occurred several times a day.","Mussten Sie sich schon ubergeben?","Wiederholtes Erbrechen, zuletzt gallig.","Gastrointestinal",["gi","vomiting"])
add("fsp_v_58","der Durchfall","der",None,"diarrhea","Haufiger, dunner Stuhlgang.","Seit drei Tagen leidet der Patient unter wassrigem Durchfall.","For three days the patient has had watery diarrhea.","Haben Sie Durchfall? Wie oft am Tag?","Wassrige Diarrhoe, 5-6 Stuhle pro Tag.","Gastrointestinal",["gi","diarrhea"])
add("fsp_v_59","die Verstopfung","die",None,"constipation","Wenn der Stuhlgang selten und hart ist.","Die Verstopfung besteht seit mehreren Tagen.","Constipation has been present for several days.","Hatten Sie in letzter Zeit Probleme mit dem Stuhlgang?","Seit 5 Tagen Obstipation trotz Laxanzien.","Gastrointestinal",["gi","constipation"])
add("fsp_v_60","der Oberbauchschmerz","der","die Oberbauchschmerzen","epigastric pain","Schmerzen im oberen Bereich des Bauches.","Der Patient klagt uber Oberbauchschmerzen nach den Mahlzeiten.","The patient complains of epigastric pain after meals.","Wo genau tut der Bauch weh? Hier oben oder eher unten?","Epigastrische Schmerzen mit Ausstrahlung in den Rucken.","Gastrointestinal",["gi","pain"])
add("fsp_v_61","der Unterbauchschmerz","der","die Unterbauchschmerzen","lower abdominal pain","Schmerzen im unteren Bereich des Bauches.","Die Unterbauchschmerzen sind rechts starker als links.","The lower abdominal pain is worse on the right than the left.","Tut es hier unten rechts weh?","Rechtsseitige Unterbauchschmerzen, Verdacht auf Appendizitis.","Gastrointestinal",["gi","pain"])
add("fsp_v_62","die Gastritis","die","die Gastritiden","gastritis","Entzundung der Magenschleimhaut.","Die Gastroskopie zeigte eine erosive Gastritis.","Gastroscopy showed erosive gastritis.","Ihre Magenschleimhaut ist entzundet.","Erosive Antrumgastritis, Helicobacter-pylori-negativ.","Gastrointestinal",["gi","gastritis"])
add("fsp_v_63","das Magengeschwur","das","die Magengeschwure","gastric ulcer","Ein Loch oder eine offene Wunde in der Magenschleimhaut.","Der Patient hat ein blutendes Magengeschwur.","The patient has a bleeding gastric ulcer.","Sie haben ein Geschwur im Magen, das blutet.","Ulcus ventriculi mit Forrest-IIa-Lasion.","Gastrointestinal",["gi","ulcer"])
add("fsp_v_64","die Pankreatitis","die","die Pankreatitiden","pancreatitis","Entzundung der Bauchspeicheldruse.","Der Patient wird wegen einer akuten Pankreatitis stationar behandelt.","The patient is treated inpatient for acute pancreatitis.","Ihre Bauchspeicheldruse ist entzundet.","Akute Pankreatitis, bilare Genese.","Gastrointestinal",["gi","pancreatitis"])
add("fsp_v_65","die Appendizitis","die","die Appendizitiden","appendicitis","Entzundung des Wurmfortsatzes (Blinddarm).","Der Patient hat eine akute Appendizitis und muss operiert werden.","The patient has acute appendicitis and needs surgery.","Ihr Blinddarm ist entzundet. Wir mussen ihn operativ entfernen.","Akute Appendizitis, sonografisch nachgewiesen.","Gastrointestinal",["gi","appendicitis"])

# 66-75: Neurology
add("fsp_v_66","der Schlaganfall","der","die Schlaganfalle","stroke","Unterbrechung der Blutversorgung im Gehirn.","Der Patient wurde mit Verdacht auf Schlaganfall eingeliefert.","The patient was admitted with suspected stroke.","Sie haben einen Schlaganfall, eine Durchblutungsstorung im Gehirn.","Akuter ischamischer Schlaganfall im Mediaversorgungsgebiet links.","Neurology",["neuro","stroke"])
add("fsp_v_67","der Schwindel","der",None,"dizziness","Gefuhl, dass sich alles dreht oder man unsicher auf den Beinen ist.","Der Schwindel tritt plotzlich auf und halt etwa 30 Sekunden an.","Dizziness appears suddenly and lasts about 30 seconds.","Ist Ihnen schwindelig? Dreht sich alles?","Anfallsartiger Drehschwindel mit Nystagmus, Verdacht auf benignen paroxysmalen Lagerungsschwindel.","Neurology",["neuro","dizziness"])
add("fsp_v_68","die Lahnung","die","die Lahnungen","paralysis","Wenn man einen Korperteil nicht mehr bewegen kann.","Der Patient zeigt eine Lahnung der rechten Korperseite.","The patient shows paralysis of the right side of the body.","Konnen Sie beide Arme und Beine bewegen?","Hemiparese rechts, Betonung des Arms.","Neurology",["neuro","paralysis"])
add("fsp_v_69","die Migrane","die","die Migranen","migraine","Starke, oft einseitige Kopfschmerzen.","Die Migraneattacken treten etwa einmal pro Monat auf.","Migraine attacks occur about once a month.","Haben Sie starke, pochende Kopfschmerzen auf einer Seite?","Migrane mit Aura, typische einseitige Kopfschmerzen mit Übelkeit.","Neurology",["neuro","migraine"])
add("fsp_v_70","der Krampfanfall","der","die Krampfanfalle","seizure","Unkontrollierte Zuckungen des Korpers, oft mit Bewusstseinsverlust.","Der Patient hatte gestern einen ersten Krampfanfall.","The patient had a first seizure yesterday.","Hatten Sie schon einmal einen Krampfanfall?","Generalisierter tonisch-klonischer Krampfanfall, Erstmanifestation.","Neurology",["neuro","seizure"])
add("fsp_v_71","die Epilepsie","die","die Epilepsien","epilepsy","Wiederkehrende Krampfanfalle aufgrund einer neurologischen Erkrankung.","Der Patient hat eine bekannte Epilepsie und nimmt regelmasig Medikamente.","The patient has known epilepsy and takes regular medication.","Sie haben eine Epilepsie, das bedeutet eine Neigung zu Krampfanfallen.","Bekannte fokale Epilepsie unter Levetiracetam-Therapie.","Neurology",["neuro","epilepsy"])
add("fsp_v_72","der Kopfschmerz","der","die Kopfschmerzen","headache","Schmerzen im Bereich des Kopfes.","Die Kopfschmerzen sind seit Tagen kontinuierlich vorhanden.","The headaches have been